import {api,image} from '../api.js';
import {esc,attr,title,status,typeLabel,sources,retryJobs,area,field} from '../ui.js';
import {go,refreshWeek,toast,refreshClinic} from '../app.js';
import {styleField,contactFields,contactCopy} from '../content-form.js';
let edit=false,editBrief=false,currentId='',currentItem=null;
export async function render(state,params){
 const id=params.get('id');if(!id)return '<a class="btn" href="#/library">Back to content</a>';
 if(currentId!==id){edit=false;editBrief=false;currentId=id;state.frame=0;}
 const data=await api(`/content/${id}`),item=data.item;currentItem=item;state.reviewItem=item;state.contentJobs=data.jobs;
 if(state.clinic?.id!==item.clinic_id){state.clinic=state.bootstrap.clinics.find(c=>c.id===item.clinic_id);await refreshClinic();}
 if(item.week_id&&state.week?.id!==item.week_id)state.week=(await api(`/weeks/${item.week_id}`)).week;
 const frame=item.frames[Math.min(state.frame,item.frames.length-1)],ready=item.frames.length>0&&item.frames.every(f=>f.assetId),working=['briefing','writing','validating','generating'].includes(item.status),copyReady=item.copy_status==='validated',copyApproved=item.copy_status==='approved',back=item.week_id?'#/week':'#/library';
 const heading=title(typeLabel(item).toUpperCase(),item.topic||'Your custom content',`${item.week_id?'Weekly content':'Standalone content'} · ${item.language}`,status(item));
 const briefForm=editBrief?`<form class="panel" data-form="brief"><h2>Your custom brief</h2>${field('Topic','topic',item.topic)}${area('Your brief','customBrief',item.brief.sourceSummary||item.brief.summary||'','Include your own message and accurate details. Rewriting a brief prepares new copy for review.')}${styleField(state,item.style_id)}${contactFields(state.clinic,item.brief.contactKeys)}<div class="form-actions"><button type="button" class="btn" data-action="cancel-brief">Cancel</button><button type="submit" class="btn primary">Save & prepare brief</button></div></form>`:'';
 const briefPanel=`<section class="panel"><div class="section-head"><div><p class="eyebrow">CONTENT BRIEF · ${esc(item.language)}</p><h2>${esc(item.brief.topic||item.topic||'Your idea')}</h2></div><button class="btn small" data-action="edit-brief" ${working?'disabled':''}>Use my own brief</button></div><p>${esc(item.brief.summary||'Preparing the brief in your selected language…')}</p>${sources(item)}${!item.frames.length&&!working?'<button class="btn primary spaced" data-action="write">Write my content →</button>':''}</section>`;
 const validation=item.validation.issues?.length?`<div class="notice error"><div><b>Copy needs a revision</b><ul>${item.validation.issues.map(v=>`<li>${esc(v)}</li>`).join('')}</ul></div></div>`:'';
 const progress=working?`<div class="generation-note panel" role="status"><span class="spinner"></span><p>${{briefing:'Preparing your brief in the selected language…',writing:'Writing content using your brief and template reference…',validating:'Checking the draft against sources and clinic facts…',generating:'Creating artwork from your approved copy…'}[item.status]}</p><button class="btn small" data-action="cancel-generation">Cancel task</button></div>`:'';
 if(!frame)return `<div class="review-top"><a href="${back}">← Back to ${item.week_id?'your week':'library'}</a></div>${heading}${retryJobs(data.jobs)}${progress}${briefPanel}${briefForm}${item.status==='cancelled'?'<button class="btn primary spaced" data-action="write">Write my content →</button>':''}`;
 const copyForm=edit?`<form class="panel edit-form" data-form="edit"><h3>Edit your copy</h3><p class="muted small-copy">Your changes are checked before approval. Changes to text or visual concepts clear only the affected artwork.</p>${item.frames.map((f,i)=>`<details ${i===state.frame?'open':''}><summary>${item.type==='carousel'?`Slide ${i+1}`:'Content'}</summary>${area('Heading',`heading-${i}`,f.heading)}${area('Body',`body-${i}`,f.body)}${area('Visual concept',`visual-${i}`,f.visualPrompt)}</details>`).join('')}${area('Caption','caption',item.caption)}<div class="form-actions"><button type="button" class="btn" data-action="cancel-edit">Cancel</button><button type="submit" class="btn primary">Save & validate</button></div></form>`:'';
 return `<div class="review-top"><a href="${back}">← Back to ${item.week_id?'your week':'library'}</a></div>${heading}${retryJobs(data.jobs)}${progress}${briefPanel}${briefForm}${validation}<div class="review-layout"><section class="art-panel"><div class="review-canvas ${item.type}">${frame.assetId?`<img src="${image(frame.assetId)}" alt="${attr(frame.heading)} — ${attr(frame.body)}">`:`<div class="copy-preview"><small>${esc(copyApproved?'Approved copy':'COPY DRAFT')} · ${frame.position} / ${item.frames.length}</small><h2>${esc(frame.heading)}</h2><p>${esc(frame.body)}</p>${contactCopy(frame)}<span>${copyApproved?'Artwork will appear here.':item.week_id?'Weekly copy is approved automatically after validation.':'Review the words before creating artwork.'}</span></div>`}</div>${item.frames.length>1?`<div class="frame-strip">${item.frames.map((f,i)=>`<button class="${i===state.frame?'selected':''}" data-action="frame" data-index="${i}" aria-label="View slide ${i+1}" aria-pressed="${i===state.frame}">${f.assetId?`<img src="${image(f.assetId,'thumbnail')}" alt="">`:'<span>✦</span>'}<small>${i+1}</small></button>`).join('')}</div>`:''}</section><section class="review-details"><div class="panel"><p class="eyebrow">${copyApproved?'APPROVED COPY':'REVIEW YOUR COPY'}</p><h2>${esc(frame.heading)}</h2><p class="slide-copy">${esc(frame.body)}</p>${contactCopy(frame)}<details><summary>Visual concept</summary><p>${esc(frame.visualPrompt)}</p></details><p class="muted small-copy">${copyReady?'✓ Draft passed factual and language validation.':copyApproved?'✓ Copy approved.':item.copy_status==='rejected'?'Revise the issues above, then validate again.':'Validation is required before approval.'}</p></div><div class="panel caption-panel"><div class="section-head"><h3>Your caption</h3><button class="btn small" data-action="copy-caption">Copy ↗</button></div><p class="caption">${esc(item.caption)}</p></div>${copyForm}<div class="review-actions">${!copyApproved&&!item.week_id?`<button class="btn primary full large" data-action="approve-copy" ${!copyReady||working?'disabled':''}>Approve copy & create artwork →</button>`:ready?`<button class="btn primary full large" data-action="approve" ${item.status==='approved'?'disabled':''}>${item.status==='approved'?'✓ Approved':'✓ Approve artwork'}</button>`:copyApproved&&!working?'<button class="btn primary full" data-action="generate">Create remaining artwork →</button>':''}<div class="two-col"><button class="btn" data-action="edit" ${working?'disabled':''}>Edit copy</button><button class="btn" data-action="write" ${working?'disabled':''}>Rewrite draft ↻</button></div><button class="btn full" data-action="download" ${!ready?'disabled':''}>Download ${item.type==='carousel'?'carousel':'artwork'} ↓</button></div></section></div>`;
}
export async function action(name,el,state){const item=currentItem;
 if(name==='frame'){state.frame=Number(el.dataset.index);go(`/review?id=${currentId}`);return;}
 if(name==='edit'||name==='cancel-edit'){edit=name==='edit';editBrief=false;go(`/review?id=${currentId}`);return;}
 if(name==='edit-brief'||name==='cancel-brief'){editBrief=name==='edit-brief';edit=false;go(`/review?id=${currentId}`);return;}
 if(name==='copy-caption'){await navigator.clipboard.writeText(item.caption);toast('Caption copied.');return;}
 if(name==='download'){const {downloadPack}=await import('../export.js');await downloadPack([item],state.clinic,item.week_id?state.week.week_start:item.created_at.slice(0,10));return;}
 const endpoint={write:'write','approve-copy':'approve-copy',approve:'approve',generate:'generate','cancel-generation':'cancel'}[name];
 if(endpoint){await api(`/content/${currentId}/${endpoint}`,{method:'POST',body:{}});edit=false;editBrief=false;if(item.week_id)await refreshWeek();go(`/review?id=${currentId}`);}
}
export async function submit(name,data,state){const item=currentItem;
 if(name==='edit'){await api(`/content/${item.id}`,{method:'PUT',body:{revision:item.revision,caption:data.get('caption'),frames:item.frames.map((f,i)=>({heading:data.get(`heading-${i}`),body:data.get(`body-${i}`),visualPrompt:data.get(`visual-${i}`)}))}});edit=false;toast('Changes saved. Checking your copy.');}
 if(name==='brief'){await api(`/content/${item.id}/brief`,{method:'PUT',body:{revision:item.revision,topic:data.get('topic'),customBrief:data.get('customBrief'),styleId:data.get('styleId'),contactKeys:data.getAll('contactKeys')}});editBrief=false;state.frame=0;toast('Your brief is being prepared.');}
 if(item.week_id)await refreshWeek();go(`/review?id=${currentId}`);
}
