import {api} from '../api.js';
import {esc,attr,title,badge,thumb,status,typeLabel,retryJobs} from '../ui.js';
import {go,refreshWeek,toast} from '../app.js';
export function itemCard(item){const ready=item.frames.length>0&&item.frames.every(f=>f.assetId);return `<article class="content-card"><a class="content-art ${item.type}" href="#/review?id=${item.id}" aria-label="Review ${attr(item.topic)}">${thumb(item)}<span class="art-type">${esc(typeLabel(item))}</span></a><div class="content-info"><div class="card-status">${status(item)}<small>${item.week_id?'Weekly':'Standalone'}</small></div><h3>${esc(item.topic||'Your content')}</h3><p>${esc(item.brief?.summary||item.angle||'Preparing your brief')}</p><a class="btn ${ready?'primary':''} small full" href="#/review?id=${item.id}">${ready?'Review artwork →':item.frames.length?'Review copy →':'Review brief →'}</a></div></article>`}
export async function render(state){const c=state.clinic,create='<a class="btn" href="#/create">Create content +</a>';
 if(!c)return `<div class="empty-state"><h1>Let’s set up your clinic.</h1><a class="btn primary" href="#/setup">Set up my clinic →</a></div>`;
 if(c.status!=='active')return `${title('YOUR FIRST WEEK','Your clinic comes first.','Confirm your details and choose a style.')}<a class="btn primary" href="#/setup?step=profile">Continue setup →</a>`;
 if(!state.week)return `${title('A FRESH START','Let’s plan your week.','Prepare two carousels, one post and four stories, or create your own content.',create)}<div class="panel empty-state"><h2>Your brand is ready.</h2><button class="btn primary" data-action="plan-week">Plan this week →</button><a class="btn spaced" href="#/create">Create a standalone piece</a></div>`;
 const week=state.week,items=week.items.filter(i=>state.filter==='all'||i.type===state.filter),working=week.jobs.some(j=>['queued','running'].includes(j.status)),allReady=week.total>0&&week.ready===week.total,validated=week.items.filter(i=>['validated','approved'].includes(i.copy_status)).length,copyApproved=week.items.filter(i=>i.copy_status==='approved').length;
 return `${title('YOUR CONTENT, YOUR WAY','Your week, step by step.',`Week of ${week.week_start} · ${c.name} · ${c.profile.language||'English'}`,`${create}<button class="btn" data-action="next-week">Plan next week</button>${working?'<button class="btn" data-action="cancel-week">Cancel tasks</button>':''}`)}<div class="week-stats"><div><span>Weekly content</span><b>${week.total} pieces</b></div><div><span>Copy validated</span><b>${validated} / ${week.total}</b></div><div><span>Copy approved</span><b>${copyApproved} / ${week.total}</b></div><div><span>Artwork ready</span><b>${week.ready} / ${week.total}</b></div></div>${retryJobs(week.jobs)}<div class="panel plan-footer"><div><h3>${allReady?'Your artwork is ready to review.':working?'Your content is being prepared.':validated===week.total?'Validated copy is ready for artwork.':'Create your week from useful briefs.'}</h3><p>${allReady?'Approve each piece or the whole week, then download your pack.':'Weekly copy is written, validated and approved automatically. Review the finished artwork, or open a brief to add your own content.'}</p></div><div class="heading-actions">${allReady?`<button class="btn primary" data-action="approve-week" ${week.status==='approved'?'disabled':''}>${week.status==='approved'?'✓ Week approved':'Approve artwork'}</button><button class="btn" data-action="download-week">Download pack ↓</button>`:`<button class="btn primary" data-action="generate-week" ${working?'disabled':''}>${week.status==='cancelled'?'Resume content':'Create my week'} →</button>`}</div></div><div class="section-head"><div class="tabs" role="group" aria-label="Content format">${[['all','All content'],['carousel','Carousels'],['post','Posts'],['story','Stories']].map(([v,label])=>`<button class="${state.filter===v?'active':''}" data-action="filter" data-filter="${v}">${label} <span>${v==='all'?week.total:week.items.filter(i=>i.type===v).length}</span></button>`).join('')}</div></div><div class="content-grid">${items.map(itemCard).join('')}</div>`;
}
export async function action(name,el,state){if(name==='filter'){state.filter=el.dataset.filter;go('/week');return;}
 if(name==='plan-week'){state.week=(await api(`/clinics/${state.clinic.id}/weeks`,{method:'POST',body:{}})).week;go('/week');return;}
 if(name==='next-week'){const date=new Date(`${state.week.week_start}T12:00:00Z`);date.setUTCDate(date.getUTCDate()+7);state.week=(await api(`/clinics/${state.clinic.id}/weeks`,{method:'POST',body:{weekStart:date.toISOString()}})).week;go('/week');return;}
 if(name==='download-week'){const {downloadPack}=await import('../export.js');await downloadPack(state.week.items,state.clinic,state.week.week_start);toast('Your artwork and captions are ready.');return;}
 const path={'cancel-week':'cancel','generate-week':'generate','approve-week':'approve'}[name];if(path){state.week=(await api(`/weeks/${state.week.id}/${path}`,{method:'POST',body:{}})).week;go('/week');}
}
