import {api,setCsrf,apiCacheRevision} from './api.js';
import {shell,esc} from './ui.js';
const app=document.querySelector('#app');
export const state={me:null,bootstrap:{clinics:[],activation:{},capabilities:{}},clinic:null,styles:[],jobs:[],week:null,filter:'all',frame:0,busy:false};
let renderToken=0,poll=null,lastView='',lastError='',workspaceClinicId=null;const views=new Map();
export async function ensureWeek(){if(!state.clinic||state.clinic.status!=='active'){state.week=null;return;}if(state.week?.clinic_id===state.clinic.id){state.week=(await api(`/weeks/${state.week.id}`)).week;return;}state.week=(await api(`/clinics/${state.clinic.id}/weeks?latest=1`)).week;}
const pages={admin:()=>import('./pages/admin.js'),welcome:()=>import('./pages/welcome.js'),setup:()=>import('./pages/setup.js'),week:()=>import('./pages/week.js'),create:()=>import('./pages/create.js'),review:()=>import('./pages/review.js'),library:()=>import('./pages/library.js'),brand:()=>import('./pages/brand.js'),settings:()=>import('./pages/settings.js')};
export function toast(message,error=false){const el=document.querySelector('#toast');el.textContent=message;el.className=`visible ${error?'error':''}`;clearTimeout(el.timer);el.timer=setTimeout(()=>el.className='',6000)}
export function go(route){if(location.hash===`#${route}`)render();else location.hash=route}
export async function refreshClinic(){if(!state.clinic)return;const clinicId=state.clinic.id,data=await api(`/clinics/${clinicId}`,{cache:false});if(state.clinic?.id!==clinicId)return;workspaceClinicId=clinicId;state.clinic=data.clinic;state.styles=data.styles;state.jobs=data.jobs;const index=state.bootstrap.clinics.findIndex(c=>c.id===data.clinic.id);if(index<0)state.bootstrap.clinics.unshift(data.clinic);else state.bootstrap.clinics[index]=data.clinic;return data}
export async function saveProfile(values){const save=()=>api(`/clinics/${state.clinic.id}/profile`,{method:'PUT',body:{...values,revision:state.clinic.revision}});let data;try{data=await save()}catch(error){if(error.status!==409)throw error;await refreshClinic();data=await save();}state.clinic=data.clinic;const index=state.bootstrap.clinics.findIndex(c=>c.id===data.clinic.id);if(index>=0)state.bootstrap.clinics[index]=data.clinic;return data}
export async function refreshWeek(){if(!state.week)return;const data=await api(`/weeks/${state.week.id}`,{cache:false});state.week=data.week;return data}
export async function refreshReview(id){const data=await api(`/content/${id}`,{cache:false});if(new URLSearchParams(route().split('?')[1]).get('id')===id){state.reviewItem=data.item;state.contentJobs=data.jobs;}return data}
export function route(){if(['#features','#how','#faq','#pricing','#marketing-main'].includes(location.hash))return '/welcome';return (location.hash.slice(1)|| (state.me?(state.clinic?'/week':'/setup'):'/welcome'))}
export async function render(){const started=performance.now(),token=++renderToken;clearTimeout(poll);const current=route(),[path,query='']=current.split('?'),name=path.split('/')[1]||'welcome';const key=pages[name]?name:'week';if(!state.me&&key!=='welcome'){location.href='/login';return}if(current!==app.dataset.route){const cached=views.get(`${state.clinic?.id||''}:${current}`);if(cached&&cached.revision===apiCacheRevision()){app.innerHTML=cached.html;app.dataset.route=current;lastView=cached.html;}else{app.innerHTML=['welcome','setup'].includes(key)?'<div class="boot" role="status">Opening your studio…</div>':shell(state,current,'<div class="panel" role="status"><span class="spinner"></span> Loading your page…</div>');lastView='';}}
try{const page=await pages[key]();if(token!==renderToken)return;if(['setup','brand','create','review'].includes(key)&&state.clinic&&workspaceClinicId!==state.clinic.id&&!(key==='setup'&&['source','goals'].includes(new URLSearchParams(query).get('step')))){await refreshClinic();if(token!==renderToken)return;}const result=await page.render(state,new URLSearchParams(query));if(token!==renderToken)return;const full=['welcome','setup'].includes(key)?result:shell(state,current,result);if(full!==lastView||current!==app.dataset.route){const focus=document.activeElement;const editing=current===app.dataset.route&&((focus&&focus.matches('input,textarea,select')&&app.contains(focus))||app.querySelector('form[data-dirty=true]'));if(!editing){app.innerHTML=full;app.dataset.route=current;lastView=full;views.set(`${state.clinic?.id||''}:${current}`,{html:full,revision:apiCacheRevision()});page.mounted?.(state,new URLSearchParams(query));}}app.dataset.renderMs=String(Math.round(performance.now()-started));lastError='';const activeJobs=(key==='setup'?state.jobs:key==='review'?(state.contentJobs||[]):(state.week?.jobs||[])).some(j=>['queued','running'].includes(j.status));if((key==='setup'&&activeJobs)||(['week','review'].includes(key)&&activeJobs))poll=setTimeout(async()=>{if(document.hidden){poll=setTimeout(()=>render(),5000);return;}try{await (key==='setup'?refreshClinic():key==='week'?refreshWeek():refreshReview(new URLSearchParams(query).get('id')));await render()}catch(e){toast(e.message,true)}},2500)}catch(error){if(token!==renderToken)return;toast(error.message,true);if(!lastView)app.innerHTML=`<div class="boot"><h1>We couldn’t open this page.</h1><p>${esc(error.message)}</p><button class="btn primary" data-action="reload">Try again</button></div>`;if(error.message!==lastError)console.error(error);lastError=error.message}}
async function act(handler,element,event){if(state.busy)return;state.busy=true;const button=element?.tagName==='BUTTON',old=button?element.textContent:'';if(button){element.disabled=true;element.setAttribute('aria-busy','true')}try{await handler()}catch(e){toast(e.message,true)}finally{state.busy=false;// Only buttons get their label restored: assigning textContent to a <select> deletes its options.
if(button&&element.isConnected){element.disabled=false;element.removeAttribute('aria-busy');if(old)element.textContent=old}}}
app.addEventListener('click',async event=>{const el=event.target.closest('[data-action]');if(!el)return;event.preventDefault();const action=el.dataset.action;if(action==='reload')return location.reload();if(action==='sign-out')return act(async()=>{if(state.me?.account?.id==='local'){sessionStorage.setItem('srshti-local-signed-out','1')}else await api('/api/auth/logout',{method:'POST',body:{}});try{localStorage.removeItem('srshti-clinic')}catch{}location.replace('/');},el,event);if(action==='dismiss-error'){let dismissed=[];try{dismissed=JSON.parse(sessionStorage.getItem('dismissed-generation-errors')||'[]')}catch{}if(!dismissed.includes(el.dataset.id))dismissed.push(el.dataset.id);sessionStorage.setItem('dismissed-generation-errors',JSON.stringify(dismissed));el.closest('.notice')?.remove();return}if(action==='retry')return act(async()=>{await api(`/jobs/${el.dataset.id}/retry`,{method:'POST',body:{}});await refreshClinic();if(state.week)await refreshWeek();render()},el,event);const page=await (pages[(route().split('?')[0].split('/')[1]||'welcome')]||pages.week)();if(page.action){if(['section','demo-step','pause-demo'].includes(action))page.action(action,el,state,event);else act(()=>page.action(action,el,state,event),el,event)}});
app.addEventListener('input',event=>{const form=event.target.closest('form');if(form)form.dataset.dirty='true'});
app.addEventListener('submit',async event=>{event.preventDefault();const form=event.target;if(!form.matches('[data-form]'))return;const name=route().split('?')[0].split('/')[1]||'welcome',page=await pages[name]();if(page.submit)act(()=>page.submit(form.dataset.form,new FormData(form),state,form),form.querySelector('button[type=submit]'),event)});
app.addEventListener('change',async event=>{const el=event.target;if(!el.matches('[data-change]'))return;const page=await pages[route().split('?')[0].split('/')[1]||'welcome']();if(page.change)act(()=>page.change(el.dataset.change,el,state),el,event)});
function preloadNavigation(event){const link=event.target.closest('a[href^="#/"]');const name=link?.getAttribute('href')?.slice(2).split(/[/?]/)[0];if(pages[name])void pages[name]().catch(()=>{});}
app.addEventListener('pointerover',preloadNavigation);app.addEventListener('focusin',preloadNavigation);
window.addEventListener('pageshow',event=>{if(event.persisted)location.reload()});
window.addEventListener('visibilitychange',()=>{if(!document.hidden)render()});
window.addEventListener('hashchange',()=>{state.reviewItem=null;state.contentJobs=[];state.frame=0;lastView='';window.scrollTo(0,0);render()});
async function start(){
 const initialPage=location.hash.slice(2).split(/[/?]/)[0];if(pages[initialPage])void pages[initialPage]().catch(()=>{});
 try{const remembered=localStorage.getItem('srshti-clinic'),params=new URLSearchParams();if(remembered)params.set('clinic',remembered);if(['setup','brand','create','review'].includes(initialPage))params.set('include','clinic');const bootstrap=await api(`/bootstrap?${params}`),me=bootstrap.me||await api('/api/me');state.me=me;setCsrf(me.csrf);state.bootstrap=bootstrap;state.clinic=bootstrap.clinics.find(c=>c.id===remembered)||bootstrap.clinics[0]||null;if(bootstrap.workspace){state.clinic=bootstrap.workspace.clinic;state.styles=bootstrap.workspace.styles;state.jobs=bootstrap.workspace.jobs;workspaceClinicId=state.clinic.id;}}catch(e){if(e.status!==401){toast(e.message,true);console.error(e)}}
 if(state.me?.account?.id==='local'){const resume=new URLSearchParams(location.search).get('workspace')==='1';if(resume){sessionStorage.removeItem('srshti-local-signed-out');history.replaceState(null,'',location.pathname+location.hash)}else if(sessionStorage.getItem('srshti-local-signed-out')==='1')state.me=null;}
 await render();
 if(state.me&&state.clinic){const clinicId=state.clinic.id,warm=()=>{
  if(document.hidden||state.busy||state.clinic?.id!==clinicId)return;
  void Promise.all([api(`/clinics/${clinicId}/library?weeks=1`),workspaceClinicId===clinicId?Promise.resolve():refreshClinic()]).catch(()=>{});
 };if(window.requestIdleCallback)window.requestIdleCallback(warm,{timeout:1000});else setTimeout(warm,0);}
}
void start();
