
export function demoPage(){return `<section class="m-bk"><div class="m-bk-in"><div class="m-bk-copy"><span class="m-bk-pill">Free · 15 minutes · Video call</span><h1>See your clinic’s content, <em>in 15 minutes.</em></h1><ul class="m-ticks"><li><b>Your brand, applied.</b> Logo, colours and style on real carousels, stories and posts.</li><li><b>A planned week.</b> How the weekly mix is created, reviewed and downloaded.</li><li><b>The plan, plainly.</b> What it costs and how credits work, with no pressure to buy.</li></ul><div class="m-fan" aria-label="Example content for Harbour Gum Dental, a fictional clinic"><img class="m-fan-l" src="/assets/demo/harbour-gum/carousel-01.webp" alt="Carousel cover: A little habit. A growing smile." width="1080" height="1350" decoding="async"><img class="m-fan-r" src="/assets/demo/harbour-gum/post-02.webp" alt="Post: Your questions are welcome." width="1080" height="1350" decoding="async"><img class="m-fan-c" src="/assets/demo/harbour-gum/story-01.webp" alt="Story: Little smiles. Big questions?" width="1080" height="1920" decoding="async"><span class="m-fan-note">Example pack for a fictional clinic</span></div><p class="m-bk-meta">With Ananth C. Jayan, founder. For practice owners, principal dentists, managers and marketing teams in AU, US, IE and UK.</p><p class="m-bk-fine">Founding plan: $80 USD/month for the first 100 paid clinics, plus applicable taxes. Content creation only; we don’t publish posts or promise patient enquiries. <a href="/pricing/">Pricing</a> · <a href="/samples/">Sample styles</a></p><div class="m-sample-alt"><div><b>Not ready for a call?</b><span>Get one free five-slide carousel in your clinic’s branding instead.</span></div>${sampleLink('Get a free sample →','btn')}</div></div><div class="m-bk-card" id="demo-booking"><h2>Pick a time</h2><div id="calendar-booking" hidden><div id="calendar-embed"></div><p id="booking-status" role="status" aria-live="polite"></p><a id="calendar-link" class="small-copy" rel="noopener noreferrer" target="_blank">Calendar not loading? Open it in a new tab ↗</a></div><div id="calendar-fallback"><p>Online booking is being set up. Email us and we will send you a time.</p><a class="btn primary full" href="mailto:hello@srshti.co.in?subject=Srshti%20dental%20content%20demo">Email to book a time</a></div><small>Times appear in your timezone. Please don’t include patient information. <a href="/privacy/">Privacy</a></small></div></div></section>`}

import {styleTile} from './marketing.js';
import {sampleForm,sampleLink} from './sample-offer.js';
const A='/assets/demo/harbour-gum/';
const art=(file,alt,cls='',h=1350)=>`<img class="${cls}" src="${A}${file}.webp" alt="${alt}" width="1080" height="${h}" loading="lazy" decoding="async">`;
const cta=(title,copy)=>`<section class="m-band"><h2>${title}</h2><p>${copy}</p><div class="m-actions">${sampleLink('Get a free sample carousel','btn primary large')}<a class="btn large" href="/dental-demo/">Book a 15-minute demo</a></div><small class="m-sample-note">Free · In your clinic’s branding · No card or obligation</small></section>`;
const week=[['Mon','carousel-01'],['Tue','post-01'],['Wed',''],['Thu','carousel-04'],['Fri','story-01'],['Sat','post-02'],['Sun','story-02']];

function howItWorksPage(){
 const steps=[
  ['Brand','Set up your clinic once.','Add your clinic details and logo. Colours are picked up from the logo, and you choose a sample style and tone.',['Logo and colour theme','Sample style and tone','Confirmed clinic details'],
   `<div class="m-hw-vis m-hw-brand"><div class="m-hw-logo"><img src="${A}logo.webp" alt="" width="270" height="90" loading="lazy"></div><div class="m-hw-dots"><i style="--c:#0e5e66"></i><i style="--c:#7ee0d6"></i><i style="--c:#f4efe6"></i><i style="--c:#1d2b3a"></i></div><div class="m-hw-styles">${['mint','teal','ivory'].map(k=>`<div class="${k==='teal'?'on':''}">${styleTile(k)}</div>`).join('')}</div></div>`],
  ['Plan & create','Get a week of content.','Request a planned week of two carousels, two posts and two stories, or create a single piece from your own brief. Copy and artwork are prepared when you ask.',['Topics from reviewed sources','Copy written and checked','Artwork in your style'],
   `<div class="m-hw-vis m-hw-week">${week.filter(([,f])=>f).map(([d,f])=>`<div><img src="${A}${f}.webp" alt="" loading="lazy"><small>${d}</small></div>`).join('')}</div>`],
  ['Review & download','Approve, then share.','Check facts, copy and artwork. Edit or regenerate anything. Download the approved images and captions, and publish from your own accounts.',['Edit and regenerate','Approve every piece','Download images and captions'],
   `<div class="m-hw-vis m-hw-ready"><div class="m-hw-phone">${art('carousel-01','')}</div><div class="m-hw-chips"><span class="ok">✓ Approved</span><span>↓ little-smiles.zip</span><span>▤ caption.txt</span></div></div>`]
 ];
 return `<section class="m-pg-hero"><p class="eyebrow">HOW IT WORKS</p><h1>From your logo to a week of content. <em>In three steps.</em></h1><p>Set up your brand once. Request content when you need it. Review, download and publish on your own terms.</p></section>
<section class="m-hw"><ol class="m-hw-steps">${steps.map(([tag,title,copy,points,vis],i)=>`<li class="m-hw-step"><div class="m-hw-num"><span>${i+1}</span><small>${tag}</small></div>${vis}<h2>${title}</h2><p>${copy}</p><ul>${points.map(p=>`<li>${p}</li>`).join('')}</ul></li>`).join('')}</ol></section>
<section class="m-section m-pack"><div class="m-intro"><p class="eyebrow">EVERY PLANNED WEEK</p><h2>Six pieces, <em>one consistent look.</em></h2><p>Your monthly credits cover planned weeks and individual pieces, including revisions.</p></div><div class="m-pack-grid"><figure class="m-pack-carousel">${art('carousel-01','Carousel example')}${art('carousel-04','Second carousel example')}<figcaption><b>2 carousels</b>5 slides each</figcaption></figure><figure>${art('post-01','Post example')}${art('post-02','Second post example')}<figcaption><b>2 posts</b>Single image, 4:5</figcaption></figure><figure class="m-pack-story">${art('story-01','Story example','',1920)}${art('story-02','Second story example','',1920)}<figcaption><b>2 stories</b>Tall 9:16 format</figcaption></figure></div></section>
<section class="m-section m-roles-split"><div class="m-intro"><p class="eyebrow">CLEAR RESPONSIBILITIES</p><h2>Srshti prepares. <em>Your team decides.</em></h2></div><div class="m-split"><article><h3>Srshti</h3><ul><li>Plans topics from reviewed patient-information sources</li><li>Writes slide copy and captions</li><li>Designs artwork with your logo and style</li><li>Flags guarantees, invented numbers and unsupported claims</li></ul></article><article class="you"><h3>Your team</h3><ul><li>Confirms clinic details and brand</li><li>Reviews and approves every piece</li><li>Downloads and publishes from your own accounts</li><li>Remains responsible for local advertising rules</li></ul></article></div><p class="m-note center">Srshti does not connect to social accounts, schedule or publish posts. Generation starts when you request it. Never upload patient records, identifiable patient photos or sensitive health information.</p></section>
${cta('See it with your clinic’s brand.','A 15-minute walkthrough of the full workflow, with no obligation.')}`}

function samplesPage(){
 const slides=[['Hook','A little habit. A growing smile.','carousel-01'],['Context','Growing smiles. Individual advice.','carousel-02'],['Support','Keep it kind. Keep it calm.','carousel-03'],['Action','A check-up. A conversation.','carousel-04'],['Invitation','Let’s talk about little smiles.','carousel-05']];
 const singles=[['Post','Hello, Harbour Gum.','post-01',1350],['Story','Little smiles. Big questions?','story-01',1920],['Story','Take a look inside.','story-02',1920],['Post','Your questions are welcome.','post-02',1350]];
 return `<section class="m-pg-hero"><p class="eyebrow">SAMPLES</p><h1>One clinic. <em>A complete content pack.</em></h1><p>Every example below was generated for Harbour Gum Dental, a fictional Melbourne clinic with invented branding. No real patients, results or endorsements.</p></section>
<section class="m-section m-sp-carousel"><div class="m-sp-phone"><div class="m-sp-bar"><img src="${A}logo.webp" alt="" width="270" height="90"><b>harbourgum</b></div><div class="m-sp-track" tabindex="0" aria-label="Carousel slides, scroll sideways">${slides.map(([,t,f],i)=>`<a href="${A}${f}.webp" data-lightbox="carousel" data-index="${i}">${art(f,`Slide ${i+1}: ${t}`)}</a>`).join('')}</div><div class="m-sp-dots">${slides.map((_,i)=>`<i class="${i?'':'on'}"></i>`).join('')}</div></div><div class="m-sp-story"><p class="eyebrow">THE CAROUSEL</p><h2>Five slides, <em>one clear story.</em></h2><ol>${slides.map(([role,t],i)=>`<li><button type="button" data-slide="${i}" aria-pressed="${i===0}"><span>${String(i+1).padStart(2,'0')}</span><div><small>${role}</small><b>${t}</b></div></button></li>`).join('')}</ol></div></section>
<section class="m-section m-sp-singles"><div class="m-intro"><p class="eyebrow">POSTS AND STORIES</p><h2>The same style, <em>in every format.</em></h2></div><div class="m-sp-grid">${singles.map(([type,t,f,h],i)=>`<a class="m-sp-card ${type.toLowerCase()}" href="${A}${f}.webp" data-lightbox="singles" data-index="${i}">${art(f,`${type}: ${t}`,'',h)}<span class="m-sp-type">${type}</span></a>`).join('')}</div></section>

${cta('Want to see your own clinic’s version?','Book a 15-minute demo, or ask for one free five-slide carousel in your brand.')}`}

export const additionalPages = {
  'free-carousel': ['Your free branded carousel', `<section class="m-hero m-sample-hero"><div class="m-hero-copy"><span class="pill">ONE FREE SAMPLE · NO PURCHASE OBLIGATION</span><h1>See your clinic. <em>In a carousel.</em></h1><p>Share your clinic’s Instagram. We’ll use your business branding to prepare one five-slide carousel, with a caption, for your team to review.</p><small>One sample per practice · No publishing or account access required</small></div></section><section class="m-section"><div class="m-demo-layout"><div><h2>Your style, before you subscribe.</h2><p>We’ll review your request, confirm the clinic and brand details by email, and agree a delivery time. Your logo, colours and visual direction guide the sample.</p><p>Use a public business Instagram profile you are authorised to share. We do not need your Instagram password, patient photos or patient information. Your team checks the final content before using it.</p><p>The paid plan is $80 USD/month plus applicable taxes for the first 100 paid clinics, with 1,000 credits. Requesting a sample does not reserve a founding place or start a subscription.</p><a class="btn" href="/dental-demo/">Prefer a 15-minute demo? →</a></div><div class="m-card">${sampleForm('sp')}</div></div></div></section>`],
  'how-it-works': ['How Srshti works', howItWorksPage()],
  samples: ['Sample dental content', samplesPage()],
  'dental-demo': ['Dental content demo', demoPage()]
};
