import {esc,attr} from './ui.js';
export function publishingPanel(item,data){
 if(!data)return `<div class="panel spaced"><h3>Publish with PostPilot</h3><p>Send your approved carousel to Instagram now or schedule it for later.</p><button class="btn full spaced" data-action="postpilot-open" ${item.status!=='approved'?'disabled':''}>Publish or schedule →</button>${item.status!=='approved'?'<small>Approve the artwork first.</small>':''}</div>`;
 if(data.error)return `<div class="panel spaced"><h3>PostPilot connection</h3><p>${esc(data.error)}</p><button class="btn spaced" data-action="postpilot-open">Check connection</button></div>`;
 if(!data.configured)return '<div class="panel spaced"><h3>Connect PostPilot</h3><p>Connect this clinic’s PostPilot account in Settings.</p><a class="btn spaced" href="#/settings">Connect in Settings →</a></div>';
 const delivery=data.delivery,canSend=!delivery||['draft','upload_failed'].includes(delivery.status),account=data.account;
 const timezone=Intl.DateTimeFormat().resolvedOptions().timeZone;
 const remoteUrl=delivery?.results?.instagram?.url;let safeUrl='';try{if(new URL(remoteUrl).protocol==='https:')safeUrl=remoteUrl}catch{}
 return `<div class="panel spaced"><h3>Instagram · PostPilot</h3><p>${esc(account?.username||account?.name||account?.displayName||'Connected Instagram account')}</p>${delivery?`<p role="status">Status: <b>${esc(delivery.status)}</b>${delivery.scheduledFor?` · ${esc(new Date(delivery.scheduledFor).toLocaleString())}`:''}</p>${delivery.lastError||delivery.error?`<p>${esc(delivery.lastError||delivery.error)}</p>`:''}${safeUrl?`<a class="btn spaced" href="${attr(safeUrl)}" target="_blank" rel="noopener noreferrer">View Instagram post ↗</a>`:''}<button class="btn small spaced" data-action="postpilot-refresh">Refresh status</button>${delivery.status==='failed'?'<button class="btn small spaced" data-action="postpilot-retry">Retry failed publication</button>':''}`:''}${canSend?`<form data-form="postpilot" class="spaced"><label class="field">Send carousel<select name="action" data-change="postpilot-action"><option value="publish">Publish now</option><option value="schedule">Schedule for later</option></select></label><label class="field" data-postpilot-schedule hidden>Publication time<input type="datetime-local" name="scheduledFor"><small>Time zone: ${esc(timezone)}. PostPilot processes scheduled posts at minute intervals.</small></label><p class="small-copy">Send all ${item.frames.length} slides and the caption shown above to this account.</p><button class="btn primary full spaced" type="submit" ${item.status!=='approved'?'disabled':''}>Send to PostPilot</button></form>`:''}</div>`;
}

export function publishingChange(name,el){if(name==='postpilot-action'){const label=el.form.querySelector('[data-postpilot-schedule]');label.hidden=el.value!=='schedule';label.querySelector('input').required=el.value==='schedule';}}
