import {image} from './api.js';
export const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const attr=esc;
export const icons={create:'✦',spark:'✦',week:'▦',library:'▤',brand:'◈',settings:'⚙',leads:'✉',check:'✓',arrow:'↗',more:'···'};
export const badge=(text,kind='')=>`<span class="badge ${kind}">${esc(text)}</span>`;
export const title=(eyebrow,heading,subtitle,actions='')=>`<div class="page-heading"><div><p class="eyebrow">${esc(eyebrow)}</p><h1>${esc(heading)}</h1><p class="muted">${esc(subtitle)}</p></div>${actions?`<div class="heading-actions">${actions}</div>`:''}</div>`;
export const field=(label,name,value='',type='text',hint='')=>`<label class="field">${esc(label)}<input name="${name}" type="${type}" value="${attr(value)}" ${type==='url'?'placeholder="https://yourclinic.com"':''}>${hint?`<small>${esc(hint)}</small>`:''}</label>`;
export const area=(label,name,value='',hint='')=>`<label class="field">${esc(label)}<textarea name="${name}" rows="3">${esc(value)}</textarea>${hint?`<small>${esc(hint)}</small>`:''}</label>`;
export function status(item){const values={approved:['Approved','good'],skipped:['Skipped','warn'],cancelled:['Paused','warn'],failed:['Needs attention','warn'],ready:['Review artwork','violet'],generating:['Creating artwork','violet'],briefing:['Preparing content','violet'],writing:['Writing copy','violet'],validating:['Checking copy','violet'],copy_review:[item.copy_status==='rejected'?'Copy needs revision':'Review copy',item.copy_status==='rejected'?'warn':'violet'],planned:['Ready to prepare','']};const [label,kind]=values[item.status]||['Planned',''];return badge(label,kind)}
export const typeLabel=item=>item.type==='carousel'?'Carousel · 5 slides':item.type==='story'?'Story':'Static post';
export function thumb(item){const frame=(item.frames||[]).find(f=>f.assetId);return frame?`<img src="${image(frame.assetId,'thumbnail')}" alt="${attr(item.topic)}" loading="lazy" decoding="async">`:`<div class="art-placeholder"><span>✦</span><small>${item.status==='generating'?'Creating your artwork':item.status==='failed'?'Task needs a retry':item.frames.length?'Copy ready to review':item.status==='briefing'?'Preparing your content':'Start with your topic'}</small></div>`}
export const sources=item=>`<details class="sources"><summary>${item.brief?.origin==='custom'?'Your supplied brief':'Sources & facts'} <span>↗</span></summary><p>${item.brief?.origin==='custom'?'Based on your supplied content and confirmed clinic facts.':'Built from reviewed patient information.'}</p>${(item.sources||[]).map(s=>/^https?:\/\//.test(s.url)?`<a href="${attr(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)} ↗</a>`:'').join('')}${(item.brief?.facts||[]).map(f=>`<p class="small-copy">${esc(f)}</p>`).join('')}</details>`;
export function retryJobs(jobs){let dismissed=new Set();try{dismissed=new Set(JSON.parse(sessionStorage.getItem('dismissed-generation-errors')||'[]'))}catch{}return jobs.filter(j=>['failed','cancelled'].includes(j.status)&&j.error!=='Content skipped.'&&!dismissed.has(j.id)).map(j=>`<div class="notice error"><span>${esc(j.error||'This task could not be completed.')}</span><button class="btn small" data-action="retry" data-id="${attr(j.id)}">Retry ${esc({style:'style',frame:'artwork',brief:'brief',writing:'writing',validation:'validation',analyze:'clinic lookup'}[j.kind]||'task')}</button><button class="notice-dismiss" data-action="dismiss-error" data-id="${attr(j.id)}" aria-label="Dismiss error" title="Dismiss">×</button></div>`).join('')}
export function steps(current){return `<ol class="steps">${['Your clinic','Your goals','Clinic details','Your style'].map((s,i)=>`<li class="${i===current?'current':i<current?'complete':''}"><span>${i<current?'✓':i+1}</span>${s}</li>`).join('')}</ol>`}
export const logoutButton=state=>state.me?'<button type="button" class="btn small logout-button" data-action="sign-out">Log out</button>':'';
export function shell(state,route,content){const c=state.clinic;const selected=route.split('?')[0];return `<div class="workspace"><aside class="sidebar"><a class="wordmark" href="#/week"><span class="brand-mark">s</span>srshti<span class="v4">studio</span></a><div class="clinic-switch"><span class="clinic-avatar">${esc((c?.name||'C').slice(0,1))}</span><div><b>${esc(c?.name||'Your clinic')}</b><small>Your content studio</small></div></div><nav aria-label="Studio">${[['/week','week','This week'],['/create','create','Create content'],['/library','library','Content library'],['/brand','brand','Brand & styles'],['/settings','settings','Settings'],...(state.me?.isAdmin?[['/admin','settings','Admin dashboard'],['/leads','leads','Leads']]:[])].map(([link,ico,name])=>`<a href="#${link}" class="${selected.startsWith(link)?'selected':''}"><span>${icons[ico]}</span>${name}</a>`).join('')}</nav><div class="sidebar-bottom"><div class="tiny-card"><span>✦</span><b>A little less on your plate.</b><p>Your next week starts here.</p></div>${state.me?.isAdmin||state.bootstrap.capabilities.local?'<a href="/legacy.html">Advanced studio ↗</a>':''}<small>${esc(state.me?.user?.email||'')}</small></div></aside><div class="workspace-body"><header class="topbar"><a class="mobile-wordmark" href="#/week">✦ srshti</a><span class="topbar-title">Your weekly content studio</span><div>${state.bootstrap.capabilities.local?badge('Local workspace','good'):''}${state.bootstrap.activation.active?badge('Clinic access active','good'):badge('Awaiting activation','warn')}<span class="account-avatar">${esc((state.me?.user?.email||'C')[0].toUpperCase())}</span>${logoutButton(state)}</div></header><main id="main" tabindex="-1">${content}</main><nav class="mobile-nav" aria-label="Mobile studio">${[['/week','▦','Week'],['/create','✦','Create'],['/library','▤','Library'],['/brand','◈','Brand'],['/settings','⚙','Settings'],...(state.me?.isAdmin?[['/admin','⚙','Admin'],['/leads','✉','Leads']]:[])].map(([link,ico,name])=>`<a href="#${link}" class="${selected.startsWith(link)?'selected':''}">${ico}<small>${name}</small></a>`).join('')}</nav></div></div>`}
