import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { spawn } from 'node:child_process';
import { deflateRawSync } from 'node:zlib';
import { buildCodexPrompt } from '../server/codex.mjs';
import { buildSlideImagePrompt } from '../server/image-providers.mjs';
import { BUSINESS_PACKS, resolveBusinessContext } from '../server/business-packs.mjs';
import { parseZip } from '../server/template-import.mjs';

const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9Z3xkAAAAASUVORK5CYII=','base64');
function crc32(buf){let c=0xffffffff;for(const b of buf){c^=b;for(let i=0;i<8;i++)c=(c&1)?0xedb88320^(c>>>1):c>>>1}return(c^0xffffffff)>>>0}
function zip(entries,{deflate=false}={}){const locals=[],centrals=[];let offset=0;for(const [name,data] of entries){const n=Buffer.from(name),raw=Buffer.from(data),packed=deflate?deflateRawSync(raw):raw,method=deflate?8:0,crc=crc32(raw),lh=Buffer.alloc(30+n.length);lh.writeUInt32LE(0x04034b50,0);lh.writeUInt16LE(20,4);lh.writeUInt16LE(method,8);lh.writeUInt32LE(crc,14);lh.writeUInt32LE(packed.length,18);lh.writeUInt32LE(raw.length,22);lh.writeUInt16LE(n.length,26);n.copy(lh,30);locals.push(lh,packed);const cd=Buffer.alloc(46+n.length);cd.writeUInt32LE(0x02014b50,0);cd.writeUInt16LE(20,4);cd.writeUInt16LE(20,6);cd.writeUInt16LE(method,10);cd.writeUInt32LE(crc,16);cd.writeUInt32LE(packed.length,20);cd.writeUInt32LE(raw.length,24);cd.writeUInt16LE(n.length,28);cd.writeUInt32LE(offset,42);n.copy(cd,46);centrals.push(cd);offset+=lh.length+packed.length}const central=Buffer.concat(centrals),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50,0);end.writeUInt16LE(entries.length,8);end.writeUInt16LE(entries.length,10);end.writeUInt32LE(central.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...locals,central,end])}

test('five first-release business packs are isolated and complete',()=>{assert.deepEqual(BUSINESS_PACKS.map(x=>x.id),['dental','tour','salon','construction','general']);for(const p of BUSINESS_PACKS){assert.equal(p.roles.length,5);assert.equal(p.starterSlides.length,5);assert.ok(p.onboardingFields.length);assert.ok(p.reviewerChecklist.length)}});
test('context resolver never borrows dental defaults for a salon',()=>{const c=resolveBusinessContext({name:'Coastline Salon',businessPackId:'salon',profile:{services:'Hair colour',language:'english'},brand:{name:'Coastline Salon',phone:'123'}});assert.equal(c.businessPack.id,'salon');assert.equal(c.brand.name,'Coastline Salon');assert.equal(c.cta.text,'Book a session');assert.doesNotMatch(JSON.stringify(c),/Dental Clinic|OralHealth|Book a consultation/)});
test('business-neutral text and image prompts use stored context',()=>{const context=resolveBusinessContext({name:'BuildCo',businessPackId:'construction',profile:{services:'Renovation',portfolioFacts:'Completed one supplied sample project'},brand:{name:'BuildCo',phone:'555'}});const prompt=buildCodexPrompt('draft',{topic:'Renovation planning',contextSnapshot:context});assert.match(prompt,/Construction/);assert.match(prompt,/Never fabricate completed projects/);assert.doesNotMatch(prompt,/dental clinic in Kerala/i);const image=buildSlideImagePrompt({slideNumber:2,slide:{role:'Approach',heading:'Plan first',body:'Define scope before work.',visualPrompt:'architect reviewing plan'},contextSnapshot:context});assert.match(image,/BuildCo/);assert.match(image,/informational slide/i);assert.doesNotMatch(image,/Book an Appointment|dental/i)});
test('tour prompts request an attractive and accurate route map for supplied itineraries',()=>{const context=resolveBusinessContext({name:'Trail Tours',businessPackId:'tour',profile:{destinations:'Kochi, Munnar, Thekkady',approvedFacts:'Day 1 Kochi; Day 2 Munnar; Day 3 Thekkady'},brand:{name:'Trail Tours'}});const writing=buildCodexPrompt('draft',{topic:'Kerala itinerary',contextSnapshot:context});const image=buildSlideImagePrompt({slideNumber:3,slide:{role:'Itinerary',heading:'Your route',body:'Kochi to Munnar to Thekkady.',visualPrompt:'A polished route map'},contextSnapshot:context});for(const prompt of [writing,image]){assert.match(prompt,/attractive route map/i);assert.match(prompt,/route, stop order and geographic placement as accurate as possible/i);assert.match(prompt,/using only the supplied itinerary/i)}});
test('ZIP parser supports DEFLATE and rejects traversal',()=>{const good=zip([['01.png',png],['02.png',png]],{deflate:true}),entries=parseZip(good);assert.equal(entries.length,2);assert.equal(entries[0].data.length,png.length);const bad=zip([['../evil.png',png]],{deflate:true});assert.throws(()=>parseZip(bad),/Unsafe ZIP path/)});

test('SQLite repository enforces revisions and client isolation',async()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'carousel-store-'));process.env.STORAGE_ROOT=dir;const store=await import(`../server/store.mjs?x=${Date.now()}`);const a=store.createClient({name:'Salon A',businessPackId:'salon'}),b=store.createClient({name:'Salon B',businessPackId:'salon'}),p=store.createProject(a.id,{topic:'Hair care'});assert.equal(p.contextSnapshot.brand.name,'Salon A');assert.throws(()=>store.getProject(b.id,p.id),/does not belong/);const saved=store.saveProject(a.id,p.id,{expectedRevision:p.revision,topic:'Hair care',slides:p.slides.map((s,i)=>i? s:{...s,heading:'Changed',approved:true})});assert.equal(saved.revision,2);assert.equal(saved.slides[0].approved,false);assert.throws(()=>store.saveProject(a.id,p.id,{expectedRevision:1,slides:saved.slides}),e=>e.status===409);fs.rmSync(dir,{recursive:true,force:true})});

test('scoped HTTP API creates separate clients and rejects stale saves',async t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'carousel-http-')),port=44000+Math.floor(Math.random()*1000),origin=`http://127.0.0.1:${port}`;const child=spawn(process.execPath,['server/index.mjs'],{cwd:path.resolve('.'),env:{...process.env,STORAGE_ROOT:dir,PORT:String(port),HOST:'127.0.0.1',OPENAI_API_KEY:''},stdio:['ignore','pipe','pipe']});t.after(()=>{child.kill();fs.rmSync(dir,{recursive:true,force:true})});await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('server timeout')),8000);child.stdout.on('data',b=>{if(String(b).includes('Carousel Studio:')){clearTimeout(timer);resolve()}});child.on('error',reject)});async function req(url,method='GET',body){const r=await fetch(origin+url,{method,headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});return{status:r.status,data:await r.json()}}const packs=await req('/api/business-packs');assert.equal(packs.data.packs.length,5);const ca=(await req('/api/clients','POST',{name:'A Salon',businessPackId:'salon'})).data.client,cb=(await req('/api/clients','POST',{name:'B Salon',businessPackId:'salon'})).data.client;const pr=(await req(`/api/clients/${ca.id}/projects`,'POST',{topic:'Colour'})).data.project;assert.equal(pr.contextSnapshot.brand.name,'A Salon');assert.equal((await req(`/api/clients/${cb.id}/projects/${pr.id}`)).status,404);const ok=await req(`/api/clients/${ca.id}/projects/${pr.id}`,'PATCH',{expectedRevision:pr.revision,topic:'Colour',slides:pr.slides});assert.equal(ok.status,200);const stale=await req(`/api/clients/${ca.id}/projects/${pr.id}`,'PATCH',{expectedRevision:pr.revision,topic:'Colour',slides:pr.slides});assert.equal(stale.status,409);const dash=await req('/api/dashboard');assert.equal(dash.data.clients,2);assert.equal(dash.data.projects,1)});
