import {test} from 'node:test';
import assert from 'node:assert/strict';
import Database from 'better-sqlite3';
import sharp from 'sharp';
import {readFile} from 'node:fs/promises';
import {cloudV4} from '../cloudflare/v4.mjs';
import {mockContent} from './v4-fixtures.mjs';
const schema=await readFile(new URL('../cloudflare/migrations/0001_accounts_credits.sql',import.meta.url),'utf8')+await readFile(new URL('../cloudflare/migrations/0009_srshti_v4.sql',import.meta.url),'utf8')+await readFile(new URL('../cloudflare/migrations/0010_v4_manual_clinic_plan.sql',import.meta.url),'utf8')+await readFile(new URL('../cloudflare/migrations/0011_v4_content_pipeline.sql',import.meta.url),'utf8');
const png=await sharp({create:{width:240,height:180,channels:4,background:'#6960dc'}}).png().toBuffer();
function fixture(){const sqlite=new Database(':memory:');sqlite.exec(schema);sqlite.prepare("INSERT INTO accounts(id,name) VALUES('A','River Dental')").run();const queued=[],objects=new Map();const DB={prepare(sql){return {bind(...values){const stmt=sqlite.prepare(sql);return {first:async()=>stmt.get(...values)||null,run:async()=>({meta:stmt.run(...values)}),all:async()=>({results:stmt.all(...values)})}}}}};const IMAGES={async info(stream){const buffer=Buffer.from(await new Response(stream).arrayBuffer());return sharp(buffer).metadata()},input(stream){let transform={};return {transform(value){transform=value;return this},async output({format,quality}){let instance=sharp(Buffer.from(await new Response(stream).arrayBuffer()));if(transform.width)instance=instance.resize({width:transform.width,height:transform.height,fit:transform.fit==='pad'?'contain':undefined,background:transform.background||'#fff',withoutEnlargement:!transform.height});const bytes=await (format==='image/webp'?instance.webp({quality}):instance.png()).toBuffer();return {response:()=>new Response(bytes,{headers:{'Content-Type':format}})}}}}};const env={DB,IMAGES,APP_ORIGIN:'https://studio.test',OPENAI_API_KEY:'test-only',GENERATION:{send:async body=>queued.push(body.v4JobId)},STATIC:{fetch:async()=>new Response(png)},ASSETS:{put:async(key,bytes,meta)=>objects.set(key,{bytes:Buffer.from(bytes),...meta}),get:async key=>{const value=objects.get(key);return value&&{arrayBuffer:async()=>value.bytes,httpMetadata:value.httpMetadata}}}};const service=cloudV4(env);
 const call=async(path,method='GET',body)=>{const url=new URL('https://studio.test/api/v4'+path);return (await service.route(new Request(url,{method,body:body===undefined?undefined:JSON.stringify(body)}),'A',url)).json()};
 const activate=()=>{sqlite.prepare("INSERT INTO subscriptions(account_id,plan_id,plan_version,status) VALUES('A','founding-clinic',1,'manual')").run();sqlite.prepare("INSERT INTO credit_ledger(id,account_id,amount,kind,source_id) VALUES('allocation','A',900,'manual_plan','manual:2026-10')").run()};
 return {sqlite,queued,objects,env,service,call,activate};}
test('Cloud V4 manual activation gates paid work and refunds provider failures; media variants remain private',async t=>{const f=fixture();const c=(await f.call('/clinics','POST',{name:'River Dental'})).clinic;await assert.rejects(f.call(`/clinics/${c.id}/styles`,'POST',{}),/awaiting activation/);assert.equal(f.queued.length,0);f.activate();let requests=0;t.mock.method(globalThis,'fetch',async(url,options)=>{assert.equal(url,'https://api.openai.com/v1/images/edits');assert.ok(options.body instanceof FormData);assert.equal(options.body.get('model'),'gpt-image-1');if(++requests===1)return new Response('{}',{status:503});return Response.json({data:[{b64_json:png.toString('base64')}]})});await f.call(`/clinics/${c.id}/styles`,'POST',{});await Promise.all(f.queued.splice(0).map(id=>f.service.consume(id)));let data=await f.call(`/clinics/${c.id}`);assert.equal(data.styles.filter(s=>s.status==='ready').length,2);assert.equal(f.sqlite.prepare("SELECT SUM(amount) n FROM credit_ledger WHERE account_id='A'").get().n,880);const failed=data.jobs.find(j=>j.status==='failed');await f.call(`/jobs/${failed.id}/retry`,'POST',{});await f.service.consume(f.queued.shift());data=await f.call(`/clinics/${c.id}`);assert.equal(data.styles.filter(s=>s.status==='ready').length,3);assert.equal(f.sqlite.prepare("SELECT SUM(amount) n FROM credit_ledger WHERE account_id='A'").get().n,870);const asset=f.sqlite.prepare('SELECT * FROM v4_assets LIMIT 1').get();assert.ok(asset.original_key.startsWith(`A/v4/${c.id}/`));assert.equal(asset.width,240);assert.equal(asset.height,180);const response=await f.service.route(new Request(`https://studio.test/api/v4/assets/${asset.id}/thumbnail`),'A',new URL(`https://studio.test/api/v4/assets/${asset.id}/thumbnail`));assert.equal(response.headers.get('Content-Type'),'image/webp');assert.match(response.headers.get('Cache-Control'),/private/);assert.equal(response.headers.get('Vary'),'Cookie');assert.equal((await sharp(Buffer.from(await response.arrayBuffer())).metadata()).format,'webp');f.sqlite.close()});
test('Cloud V4 produces canonical carousel canvases and uses private clinic styles as references',async t=>{const f=fixture();f.activate();t.mock.method(globalThis,'fetch',async(url,options)=>{if(String(url).includes('chat/completions')){const request=JSON.parse(options.body);return Response.json({choices:[{message:{content:JSON.stringify(mockContent(request.messages[0].content[0].text,request.response_format.json_schema.schema))}}]});}return Response.json({data:[{b64_json:png.toString('base64')}]});});const c=(await f.call('/clinics','POST',{name:'River Dental'})).clinic;await f.call(`/clinics/${c.id}/profile`,'PUT',{revision:c.revision,confirmed:true});await f.call(`/clinics/${c.id}/styles`,'POST',{});await Promise.all(f.queued.splice(0).map(id=>f.service.consume(id)));const {styles}=await f.call(`/clinics/${c.id}`);await f.call(`/clinics/${c.id}/style-selection`,'PUT',{primaryStyleId:styles[0].id});const {week}=await f.call(`/clinics/${c.id}/weeks`,'POST',{});await Promise.all(f.queued.splice(0).map(id=>f.service.consume(id)));await f.call(`/weeks/${week.id}/generate`,'POST',{});while(f.queued.length)await Promise.all(f.queued.splice(0).map(id=>f.service.consume(id)));const current=(await f.call(`/weeks/${week.id}`)).week;assert.equal(current.heroReady,true);assert.equal(f.queued.length,0);const asset=f.sqlite.prepare('SELECT * FROM v4_assets WHERE id=?').get(current.items[0].frames[0].assetId),meta=await sharp(f.objects.get(asset.original_key).bytes).metadata();assert.equal(meta.width,1080);assert.equal(meta.height,1350);assert.equal(f.sqlite.prepare("SELECT SUM(amount) n FROM credit_ledger WHERE account_id='A'").get().n,692);f.sqlite.close()});
