import {test} from 'node:test';
import assert from 'node:assert/strict';
import Database from 'better-sqlite3';
import {readFile} from 'node:fs/promises';
import {createV4Service,weekStart} from '../server/v4/service.mjs';
import {KNOWLEDGE_CARDS,makeCopy,rankCards,validateCopy} from '../server/v4/knowledge.mjs';
import {publicUrl,publicFetch,extractCandidates} from '../server/v4/extract.mjs';
import {mockContent,mockProviders} from './v4-fixtures.mjs';
const pipeline=await readFile(new URL('../cloudflare/migrations/0011_v4_content_pipeline.sql',import.meta.url),'utf8');
const migration=await readFile(new URL('../cloudflare/migrations/0009_srshti_v4.sql',import.meta.url),'utf8');
function fixture(){const sqlite=new Database(':memory:');sqlite.exec(migration+pipeline);const queued=[],assets=new Map();let brokenPosition=0,generated=0,active=true,rejectValidation=false;const textCalls=[];const db={prepare(sql){return {bind(...args){const stmt=sqlite.prepare(sql);return {first:async()=>stmt.get(...args)||null,all:async()=>({results:stmt.all(...args)}),run:async()=>({meta:stmt.run(...args)})}}}}};const service=createV4Service({db,providerCatalog:async()=>mockProviders,generateText:async(input)=>{textCalls.push(input);if(input.schema.properties.valid&&rejectValidation)return {valid:false,issues:['Unsupported advice.']};return mockContent(input.prompt,input.schema);},capabilities:{demo:true},activation:async()=>({active}),requireActivation:async()=>{if(!active)throw Object.assign(Error('Awaiting activation'),{status:409})},enqueue:async id=>queued.push(id),saveImage:async(a,c,image)=>{const key=crypto.randomUUID();assets.set(key,{bytes:image.bytes,mime:image.mime});return {mime:image.mime,originalKey:key,previewKey:key,thumbnailKey:key,size:3}},readImage:async key=>assets.get(key),generateStyle:async()=>({bytes:new Uint8Array([1,2,3]),mime:'image/png'}),generateFrame:async(c,item,frame)=>{generated++;if(frame.position===brokenPosition)throw Error('Simulated provider failure');await new Promise(r=>setTimeout(r,2));return {bytes:new Uint8Array([1,2,3]),mime:'image/png'}}});
 const call=async(path,method='GET',input,account='A')=>{const url=new URL(`https://studio.test/api/v4${path}`);const res=await service.route(new Request(url,{method,body:input===undefined?undefined:JSON.stringify(input),headers:input===undefined?{}:{'Content-Type':'application/json'}}),account,url);return res.json()};
 async function drain(){let count=0;while(queued.length){const group=queued.splice(0);await Promise.all(group.map(id=>service.consume(id)));if(++count>15)throw Error('Queue did not settle')}}
 async function setup(profile={}){const c=(await call('/clinics','POST',{name:'River Dental'})).clinic;await call(`/clinics/${c.id}/profile`,'PUT',{revision:c.revision,confirmed:true,services:['General dentistry'],name:c.name,...profile});await call(`/clinics/${c.id}/styles`,'POST',{});await drain();const data=await call(`/clinics/${c.id}`);assert.equal(data.styles.length,3);await call(`/clinics/${c.id}/style-selection`,'PUT',{primaryStyleId:data.styles[0].id,secondaryStyleIds:[data.styles[1].id]});const {week}=await call(`/clinics/${c.id}/weeks`,'POST',{});await drain();return {clinic:(await call(`/clinics/${c.id}`)).clinic,week:(await call(`/weeks/${week.id}`)).week}}
 return {sqlite,service,call,queued,drain,setup,failFrame:n=>brokenPosition=n,setActive:v=>active=v,generated:()=>generated,textCalls,rejectValidation:v=>rejectValidation=v};}
test('V4 source-backed copy validates for every card, angle and format; unverified claims fail closed',()=>{const c={id:'c',name:'River Dental',brand:{},profile:{facts:[{text:'We are open on Sundays.',status:'imported'}]}};for(const card of KNOWLEDGE_CARDS)for(const angle of card.engagementAngles)for(const format of ['carousel','post','story']){const copy=makeCopy(card,angle,format,c);assert.deepEqual(validateCopy(copy.frames,copy.caption,card,c),{valid:true})}const card=KNOWLEDGE_CARDS[0],copy=makeCopy(card,card.engagementAngles[0],'post',c);for(const unsafe of ['Guaranteed painless care.','99% success.','We are open on Sundays.','Salt cures every tooth infection.'])assert.equal(validateCopy([{heading:copy.frames[0].heading,body:unsafe}],copy.caption,card,c).valid,false);c.profile.facts[0].status='verified';assert.equal(validateCopy([{heading:copy.frames[0].heading,body:'We are open on Sundays.'}],copy.caption,card,c).valid,true)});
test('V4 planning uses clinic and global cooldown history',()=>{const c={id:'c',profile:{services:[],location:'Kochi'}};const first=rankCards(c)[0],history=[{clinic_id:'c',knowledge_card_id:first.card.id,angle_id:first.angle.id,headline:first.angle.hook,region:'Kochi',generated_at:new Date().toISOString(),status:'approved'}];assert.notEqual(rankCards(c,history)[0].card.id,first.card.id);const global={...history[0],clinic_id:'other'};assert.ok(rankCards(c,[global]).find(r=>r.angle.id===first.angle.id).score<first.score);assert.equal(weekStart('2026-10-03'),'2026-09-28')});
test('V4 weekly pack prioritizes the hero, preserves parallel frames, then supports approval/export access',async()=>{const f=fixture(),{clinic,week}=await f.setup();assert.equal(week.items.length,7);assert.equal(new Set(week.items.map(i=>i.knowledge_card_id)).size,7);assert.deepEqual(week.items.map(i=>i.type),['carousel','carousel','post','story','story','story','story']);assert.equal((await f.call(`/clinics/${clinic.id}/weeks`,'POST',{})).week.id,week.id);await f.call(`/weeks/${week.id}/generate`,'POST',{});assert.equal(f.queued.length,7);assert.equal(f.sqlite.prepare("SELECT COUNT(*) n FROM v4_jobs WHERE kind='frame' AND priority=1").get().n,0);const first=f.queued.splice(0);await Promise.all(first.map(id=>f.service.consume(id)));let current=(await f.call(`/weeks/${week.id}`)).week;assert.equal(current.heroReady,false);assert.equal(current.items[0].copy_status,'approved');assert.equal(current.items[0].frames.filter(i=>i.assetId).length,0);assert.equal(f.queued.length,15);await f.drain();current=(await f.call(`/weeks/${week.id}`)).week;assert.equal(current.ready,7);assert.equal(current.status,'ready');assert.equal(f.generated(),15);const asset=current.items[0].frames[0].assetId;await assert.rejects(f.call(`/assets/${asset}/original`,'GET',undefined,'B'),/Image not found/);await assert.rejects(f.call(`/weeks/${week.id}`,'GET',undefined,'B'),/Week not found/);await assert.rejects(f.call(`/clinics/${clinic.id}`,'GET',undefined,'B'),/Clinic not found/);const approved=(await f.call(`/weeks/${week.id}/approve`,'POST',{})).week;assert.equal(approved.status,'approved');assert.ok(approved.items.every(i=>i.status==='approved'));f.sqlite.close()});
test('V4 failed frames retry without recreating successful artwork, edits regenerate only changed frames',async()=>{const f=fixture(),{week}=await f.setup();f.failFrame(3);await f.call(`/weeks/${week.id}/generate`,'POST',{});await f.drain();let current=(await f.call(`/weeks/${week.id}`)).week;assert.equal(current.heroReady,false);assert.equal(current.items[0].frames.filter(i=>i.assetId).length,4);await assert.rejects(f.call(`/weeks/${week.id}/approve`,'POST',{}),/artwork must be ready/);const failed=current.jobs.filter(j=>j.status==='failed');f.failFrame(0);for(const j of failed)await f.call(`/jobs/${j.id}/retry`,'POST',{});await f.drain();current=(await f.call(`/weeks/${week.id}`)).week;assert.equal(current.ready,7);const item=current.items[0],previous=item.frames.map(f=>f.assetId),frames=item.frames.map(f=>({heading:f.heading,body:f.body}));frames[1].body=frames[2].body;await f.call(`/content/${item.id}`,'PUT',{revision:item.revision,caption:item.caption,frames});const edited=(await f.call(`/weeks/${week.id}`)).week.items[0];assert.equal(edited.frames[0].assetId,previous[0]);assert.equal(edited.frames[1].assetId,'');await f.drain();const ready=(await f.call(`/weeks/${week.id}`)).week.items[0];assert.notEqual(ready.frames[1].assetId,previous[1]);assert.equal(ready.frames[2].assetId,previous[2]);await assert.rejects(f.call(`/content/${item.id}`,'PUT',{revision:item.revision}),/Content changed/);f.sqlite.close()});
test('V4 activation rejection leaves reviewed content intact; style choices are clinic scoped',async()=>{const f=fixture(),{clinic,week}=await f.setup();await f.call(`/weeks/${week.id}/generate`,'POST',{});await f.drain();const item=(await f.call(`/weeks/${week.id}`)).week.items[0];f.setActive(false);await assert.rejects(f.call(`/content/${item.id}/generate`,'POST',{}),/Awaiting activation/);assert.equal((await f.call(`/weeks/${week.id}`)).week.items[0].revision,item.revision);const other=(await f.call('/clinics','POST',{name:'Other'})).clinic;await assert.rejects(f.call(`/clinics/${other.id}/style-selection`,'PUT',{primaryStyleId:clinic.styleSelection.primaryStyleId}),/Choose a ready style/);await assert.rejects(f.call(`/clinics/${clinic.id}/profile`,'PUT',{revision:1,name:'stale'}),/details changed/);f.sqlite.close()});
test('V4 website imports reject private addresses, redirect escapes, oversized pages and extract candidate facts only',async()=>{for(const url of ['http://clinic.com','https://127.0.0.1','https://[::1]','https://192.168.1.1','https://clinic.local','https://u:p@clinic.com','https://clinic.com:444'])assert.throws(()=>publicUrl(url));await assert.rejects(publicFetch('https://clinic.com',async()=>new Response(null,{status:302,headers:{location:'http://127.0.0.1/'}})),/public HTTPS/);await assert.rejects(publicFetch('https://clinic.com',async()=>new Response('x'.repeat(2000001))),/too large/);const html='<title>River Dental | Home</title><meta name="theme-color" content="#112233"><script type="application/ld+json">{"@type":"Dentist","name":"River Dental","address":{"addressLocality":"Kochi"},"telephone":"+91 1234567890"}</script><p>General dentistry, whitening</p>';const extracted=extractCandidates(html,'https://clinic.com');assert.equal(extracted.name,'River Dental');assert.equal(extracted.location,'Kochi');assert.equal(extracted.primary,'#112233');assert.equal(extracted.facts[0].status,'imported')});

test('Standalone formats require copy review, send real references, and preserve selected CTA contacts',async()=>{
 const f=fixture(),{clinic,week}=await f.setup({language:'Malayalam + English',phone:'+91 1234567890',whatsapp:'+91 9876543210',address:'River Road, Kochi',website:'https://river.example.com',bookingUrl:'https://river.example.com/book'});
 assert.equal(week.ready,0);assert.ok(week.items.every(i=>i.frames.length===0));
 for(const type of ['carousel','story','post']){
  const {item}=await f.call(`/clinics/${clinic.id}/content`,'POST',{type,topic:'Clinic update',customBrief:'Our Sunday clinic is open from 10am to 1pm.',styleId:clinic.styleSelection.primaryStyleId,contactKeys:['phone','address','bookingUrl']});
  assert.equal(item.week_id,null);assert.equal(item.language,'Malayalam + English');await f.drain();
  await assert.rejects(f.call(`/content/${item.id}/generate`,'POST',{}),/approve the copy/);
  await f.call(`/content/${item.id}/write`,'POST',{});await f.drain();
  let current=(await f.call(`/content/${item.id}`)).item;
  assert.equal(current.frames.length,type==='carousel'?5:1);assert.equal(current.copy_status,'validated');assert.equal(f.generated(),type==='carousel'?0:type==='story'?5:6);
  assert.deepEqual(current.frames.at(-1).contacts,{phone:'+91 1234567890',address:'River Road, Kochi',bookingUrl:'https://river.example.com/book'});
  assert.ok(current.frames.slice(0,-1).every(frame=>Object.keys(frame.contacts).length===0));
  const writing=f.textCalls.filter(c=>c.schema.properties.frames).at(-1);assert.ok(writing.reference.bytes.length);assert.match(writing.prompt,/Malayalam \+ English/);assert.match(writing.prompt,/selected template reference/);assert.match(writing.prompt,/phone.*1234567890/s);
  await f.call(`/content/${item.id}/approve-copy`,'POST',{});await f.drain();current=(await f.call(`/content/${item.id}`)).item;assert.equal(current.status,'ready');
  await f.call(`/content/${item.id}/approve`,'POST',{});
  // Next format starts with a fresh counter comparison, using actual number of prior images.
  const before=f.generated();assert.equal(before,(type==='carousel'?5:type==='story'?6:7));
 }
 const library=(await f.call(`/clinics/${clinic.id}/library`)).items;assert.equal(library.filter(i=>i.week_id===null).length,3);assert.equal((await f.call(`/weeks/${week.id}`)).week.total,7);
 f.sqlite.close();
});

test('Provider mappings are account scoped and queued writing retains both task choices',async()=>{
 const f=fixture(),{clinic}=await f.setup();const config=await f.call('/providers');config.tasks.validation={provider:'gemini',model:'validator-a'};await f.call('/providers','PUT',{tasks:config.tasks});
 const {item}=await f.call(`/clinics/${clinic.id}/content`,'POST',{type:'post',customBrief:'Our clinic is open on Sunday.'});await f.drain();await f.call(`/content/${item.id}/write`,'POST',{});
 const queued=f.sqlite.prepare("SELECT input_json FROM v4_jobs WHERE content_id=? AND kind='writing'").get(item.id),snapshot=JSON.parse(queued.input_json);
 assert.deepEqual(snapshot.validationGeneration,{provider:'gemini',model:'validator-a'});assert.equal(snapshot.generation.model,'writer-a');
 config.tasks.writing={provider:'openai',model:'writer-b'};await f.call('/providers','PUT',{tasks:config.tasks});await f.drain();
 assert.equal(f.textCalls.filter(c=>c.schema.properties.frames).at(-1).generation.model,'writer-a');assert.equal(f.textCalls.filter(c=>c.schema.properties.valid).at(-1).generation.provider,'gemini');
 assert.equal((await f.call('/providers','GET',undefined,'B')).tasks.writing.model,'writer-a');
 config.tasks.artwork={provider:'gemini',model:'not-a-model'};await assert.rejects(f.call('/providers','PUT',{tasks:config.tasks}),/supported model/);
 f.sqlite.close();
});

test('Validation failures stop weekly artwork, and changed clinic contacts invalidate standalone approval',async()=>{
 const f=fixture(),{clinic,week}=await f.setup({phone:'+91 1234567890'});f.rejectValidation(true);await f.call(`/weeks/${week.id}/generate`,'POST',{});await f.drain();
 const rejected=(await f.call(`/weeks/${week.id}`)).week;assert.equal(f.generated(),0);assert.ok(rejected.items.every(i=>i.copy_status==='rejected'));assert.ok(rejected.items.every(i=>i.validation.issues.length));
 await assert.rejects(f.call(`/content/${rejected.items[0].id}/approve-copy`,'POST',{}),/Validate the draft/);
 f.rejectValidation(false);const {item}=await f.call(`/clinics/${clinic.id}/content`,'POST',{type:'story',customBrief:'Our clinic welcomes new patients.'});await f.drain();await f.call(`/content/${item.id}/write`,'POST',{});await f.drain();
 const latest=(await f.call(`/clinics/${clinic.id}`)).clinic;await f.call(`/clinics/${clinic.id}/profile`,'PUT',{revision:latest.revision,phone:'+91 9999999999',confirmed:true});
 await assert.rejects(f.call(`/content/${item.id}/approve-copy`,'POST',{}),/Clinic details or language changed/);
 f.sqlite.close();
});

test('Custom briefs replace weekly briefs and canceled writing cannot create stale artwork',async()=>{
 const f=fixture(),{clinic,week}=await f.setup();let item=week.items[0];
 await f.call(`/content/${item.id}/brief`,'PUT',{revision:item.revision,customBrief:'Announce our Sunday hours.',topic:'Sunday opening',contactKeys:[]});await f.drain();
 item=(await f.call(`/content/${item.id}`)).item;assert.equal(item.brief.origin,'custom');assert.equal(item.brief.sourceSummary,'Announce our Sunday hours.');assert.equal(item.knowledge_card_id,'');
 await f.call(`/content/${item.id}/write`,'POST',{});const obsolete=f.queued.splice(0);await f.call(`/content/${item.id}/cancel`,'POST',{});await Promise.all(obsolete.map(id=>f.service.consume(id)));assert.equal(f.generated(),0);
 const cancelled=(await f.call(`/content/${item.id}`)).item;await f.call(`/content/${item.id}/brief`,'PUT',{revision:cancelled.revision,customBrief:'Announce our Monday hours.',topic:'Monday opening'});await f.drain();await assert.rejects(f.call(`/jobs/${obsolete[0]}/retry`,'POST',{}),/older draft/);
 await f.call(`/content/${item.id}/write`,'POST',{});await f.drain();assert.equal((await f.call(`/content/${item.id}`)).item.status,'ready');
 f.sqlite.close();
});
