import { repairGeneration } from '../web/studio-controls.js';
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url);
let Database;
try{Database=require('better-sqlite3')}catch{const {DatabaseSync}=require('node:sqlite');Database=class{constructor(file){this.raw=new DatabaseSync(file)}exec(sql){return this.raw.exec(sql)}pragma(sql){return this.raw.exec('PRAGMA '+sql)}prepare(sql){return this.raw.prepare(sql)}transaction(fn){return (...args)=>{this.raw.exec('BEGIN IMMEDIATE');try{const v=fn(...args);this.raw.exec('COMMIT');return v}catch(e){this.raw.exec('ROLLBACK');throw e}}}}}
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { mkdir, readFile, readdir, writeFile, cp } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { getBusinessPack, resolveBusinessContext, starterSlidesForPack } from './business-packs.mjs';

const here=path.dirname(fileURLToPath(import.meta.url));
const repoRoot=path.resolve(here,'..');
export const storageRoot=path.resolve(process.env.STORAGE_ROOT||path.join(repoRoot,'storage'));
const dbPath=path.join(storageRoot,'studio.sqlite');
const assetsRoot=path.join(storageRoot,'assets');
const legacyProjectsRoot=path.join(repoRoot,'storage','projects');
const legacyTemplatesRoot=path.join(repoRoot,'web','assets','design-systems');
await mkdir(storageRoot,{recursive:true}); await mkdir(assetsRoot,{recursive:true});
export const db=new Database(dbPath);
db.pragma('foreign_keys = ON'); db.pragma('journal_mode = WAL');

db.exec(`
CREATE TABLE IF NOT EXISTS clients(id TEXT PRIMARY KEY, name TEXT NOT NULL, business_pack_id TEXT NOT NULL, revision INTEGER NOT NULL DEFAULT 1, archived INTEGER NOT NULL DEFAULT 0, profile_json TEXT NOT NULL, brand_json TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS projects(id TEXT PRIMARY KEY, client_id TEXT NOT NULL REFERENCES clients(id), revision INTEGER NOT NULL DEFAULT 1, archived INTEGER NOT NULL DEFAULT 0, business_pack_id TEXT NOT NULL, business_pack_version TEXT NOT NULL, recipe_id TEXT NOT NULL, context_json TEXT NOT NULL, project_json TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_projects_client ON projects(client_id,updated_at DESC);
CREATE TABLE IF NOT EXISTS assets(id TEXT PRIMARY KEY, client_id TEXT REFERENCES clients(id), project_id TEXT, kind TEXT NOT NULL, file_name TEXT NOT NULL, mime TEXT NOT NULL, size INTEGER NOT NULL, checksum TEXT NOT NULL, path TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_assets_client ON assets(client_id);
CREATE TABLE IF NOT EXISTS templates(id TEXT PRIMARY KEY, client_id TEXT REFERENCES clients(id), pack_id TEXT NOT NULL, pack_version TEXT NOT NULL, name TEXT NOT NULL, business_pack_id TEXT, mode TEXT NOT NULL, data_json TEXT NOT NULL, checksum TEXT NOT NULL, archived INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_templates_client ON templates(client_id,business_pack_id);
CREATE TABLE IF NOT EXISTS jobs(id TEXT PRIMARY KEY, client_id TEXT NOT NULL REFERENCES clients(id), project_id TEXT NOT NULL REFERENCES projects(id), slide_index INTEGER, stage TEXT NOT NULL, provider TEXT NOT NULL, model TEXT, input_hash TEXT NOT NULL, input_json TEXT NOT NULL, status TEXT NOT NULL, attempt INTEGER NOT NULL DEFAULT 1, result_json TEXT, error TEXT, idempotency_key TEXT, created_at TEXT NOT NULL, started_at TEXT, finished_at TEXT);
CREATE UNIQUE INDEX IF NOT EXISTS idx_jobs_idem ON jobs(client_id,project_id,idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE TABLE IF NOT EXISTS template_imports(id TEXT PRIMARY KEY, client_id TEXT REFERENCES clients(id), business_pack_id TEXT, scope TEXT NOT NULL, status TEXT NOT NULL, checksum TEXT NOT NULL, staged_path TEXT NOT NULL, preview_json TEXT NOT NULL, created_at TEXT NOT NULL, expires_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS migration_ledger(source TEXT PRIMARY KEY, checksum TEXT NOT NULL, migrated_at TEXT NOT NULL, result_json TEXT NOT NULL);
`);
const builtinInsert=db.prepare('INSERT OR IGNORE INTO templates VALUES(?,?,?,?,?,?,?,?,?,?,?)');
for(const packId of ['dental','tour','salon','construction','general']){
  const data={slides:Array.from({length:5},(_,i)=>({position:i+1,generated:true,variant:i+1}))};
  builtinInsert.run(`builtin:${packId}:neutral:1.0.0`,null,`builtin-${packId}`,'1.0.0','Neutral Starter',packId,'slides',JSON.stringify(data),`builtin-${packId}-neutral-v1`,0,new Date().toISOString());
}
const legacySpecs=[['teal-editorial-pro',.205,.744],['clinical-white',.205,.752],['warm-ivory',.064,.811],['deep-teal-premium',.181,.848],['mint-friendly',.158,.864],['airy-aqua',.160,.824],['kids-mint',.177,.866],['nature-sage',.172,.826],['warm-clinical',.205,.915],['premium-charcoal',.163,.736]];
for(const [legacyId,top,bottom] of legacySpecs){const data={staticPath:`/assets/design-systems/${legacyId}.png`,crops:Array.from({length:5},(_,position)=>({position:position+1,top,bottom,left:.006,right:.006,gap:.005}))};builtinInsert.run(`builtin:dental:legacy:${legacyId}:1.0.0`,null,'smilecraft-masters','1.0.0',legacyId.replace(/-/g,' '),'dental','board',JSON.stringify(data),`legacy-${legacyId}-v1`,0,new Date().toISOString());}
for(const [legacyId,file] of [['editorial','teal-editorial.jpg'],['friendly','friendly-clinic.jpg'],['clean','clinical-clean.jpg'],['premium','premium-dark.jpg']]){const data={slides:Array.from({length:5},(_,i)=>({position:i+1,staticPath:`/assets/${file}`}))};builtinInsert.run(`builtin:dental:legacy:${legacyId}:1.0.0`,null,'smilecraft-legacy-cards','1.0.0',legacyId,'dental','slides',JSON.stringify(data),`legacy-card-${legacyId}-v1`,0,new Date().toISOString());}
db.prepare("UPDATE jobs SET status='interrupted',finished_at=? WHERE status IN ('queued','running')").run(new Date().toISOString());
const now=()=>new Date().toISOString(); const id=()=>crypto.randomUUID(); const json=v=>JSON.stringify(v??{}); const parse=(v,f={})=>{try{return JSON.parse(v)}catch{return f}}; const hash=v=>crypto.createHash('sha256').update(v).digest('hex');
const clientRow=r=>r&&({id:r.id,name:r.name,businessPackId:r.business_pack_id,revision:r.revision,archived:Boolean(r.archived),profile:parse(r.profile_json),brand:parse(r.brand_json),createdAt:r.created_at,updatedAt:r.updated_at});
const projectRow=r=>r&&({...parse(r.project_json),id:r.id,clientId:r.client_id,revision:r.revision,archived:Boolean(r.archived),businessPackId:r.business_pack_id,businessPackVersion:r.business_pack_version,recipeId:r.recipe_id,contextSnapshot:parse(r.context_json),createdAt:r.created_at,updatedAt:r.updated_at});
export function listClients({includeArchived=false}={}){return db.prepare(`SELECT * FROM clients ${includeArchived?'':'WHERE archived=0'} ORDER BY updated_at DESC`).all().map(clientRow)}
export function getClient(clientId){return clientRow(db.prepare('SELECT * FROM clients WHERE id=?').get(clientId))}
export function createClient(input){const name=String(input.name||'').trim().slice(0,100);if(!name)throw Object.assign(new Error('Client name is required.'),{status:400});const p=getBusinessPack(input.businessPackId);const created=now(),clientId=id();const profile=input.profile&&typeof input.profile==='object'?input.profile:{};const brand={name,...(input.brand&&typeof input.brand==='object'?input.brand:{})};db.prepare('INSERT INTO clients VALUES(?,?,?,?,?,?,?,?,?)').run(clientId,name,p.id,1,0,json(profile),json(brand),created,created);return getClient(clientId)}
export function updateClient(clientId,input){const old=getClient(clientId);if(!old)throw Object.assign(new Error('Client not found.'),{status:404});if(Number(input.expectedRevision)!==old.revision)throw Object.assign(new Error('Client changed since it was loaded.'),{status:409,currentRevision:old.revision});const name=String(input.name??old.name).trim().slice(0,100)||old.name;const profile={...old.profile,...(input.profile||{})};const brand={...old.brand,...(input.brand||{}),name:String((input.brand||{}).name??old.brand.name??name).trim().slice(0,100)||name};const revision=old.revision+1;db.prepare('UPDATE clients SET name=?,revision=?,profile_json=?,brand_json=?,archived=?,updated_at=? WHERE id=?').run(name,revision,json(profile),json(brand),input.archived===undefined?Number(old.archived):Number(Boolean(input.archived)),now(),clientId);return getClient(clientId)}
export function listProjects(clientId){const rows=clientId?db.prepare('SELECT * FROM projects WHERE client_id=? AND archived=0 ORDER BY updated_at DESC').all(clientId):db.prepare('SELECT * FROM projects WHERE archived=0 ORDER BY updated_at DESC').all();return rows.map(projectRow)}
export function getProject(clientId,projectId){const r=db.prepare('SELECT * FROM projects WHERE id=?').get(projectId);if(!r)return null;if(clientId&&r.client_id!==clientId)throw Object.assign(new Error('Project does not belong to this client.'),{status:404});return projectRow(r)}
export function createProject(clientId,input={}){const client=getClient(clientId);if(!client||client.archived)throw Object.assign(new Error('Client not found.'),{status:404});const p=getBusinessPack(client.businessPackId);const created=now(),projectId=id(),context=resolveBusinessContext(client,input.contextOverrides||{});const defaultTemplate=p.id==='dental'?'builtin:dental:legacy:teal-editorial-pro:1.0.0':`builtin:${p.id}:neutral:1.0.0`;const project={schemaVersion:1,topic:String(input.topic||'').slice(0,450),key:String(input.key||'').slice(0,80),notes:String(input.notes||'').slice(0,4000),language:String(input.language||context.language).trim().slice(0,80),templateId:String(input.templateId||defaultTemplate),templateVersion:String(input.templateVersion||''),slides:Array.isArray(input.slides)&&input.slides.length===5?input.slides:starterSlidesForPack(p.id),instagram:String(input.instagram||''),youtubeTitle:String(input.youtubeTitle||''),youtubeDescription:String(input.youtubeDescription||''),generation:repairGeneration(input.generation),stage:Number(input.stage)||0,exportHistory:[]};db.prepare('INSERT INTO projects VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(projectId,clientId,1,0,p.id,p.version,context.recipe.id,json(context),json(project),created,created);return getProject(clientId,projectId)}
function normalizeSlides(project,previous){
  if(!Array.isArray(project.slides)||project.slides.length!==5) throw Object.assign(new Error('Exactly five slides are required.'),{status:400});
  return project.slides.map((s,i)=>{
    const old=previous.slides?.[i]||{};
    const changed=String(s.heading||'')!==String(old.heading||'')||String(s.body||'')!==String(old.body||'')||String(s.visualPrompt||'')!==String(old.visualPrompt||'');
    return {...old,...s,id:`slide-${i+1}`,copyRevision:changed?(Number(old.copyRevision)||1)+1:Number(s.copyRevision||old.copyRevision||1),approved:changed?false:Boolean(s.approved),approvedAt:changed?'':String(s.approvedAt||old.approvedAt||''),artwork:changed?'':String(s.artwork||old.artwork||''),artworkAssetId:changed?'':String(s.artworkAssetId||old.artworkAssetId||''),artworkReviewed:changed?false:Boolean(s.artworkReviewed),artworkReviewedAt:changed?'':String(s.artworkReviewedAt||old.artworkReviewedAt||'')};
  });
}
export function saveProject(clientId,projectId,input){const old=getProject(clientId,projectId);if(!old)throw Object.assign(new Error('Project not found.'),{status:404});if(Number(input.expectedRevision)!==old.revision)throw Object.assign(new Error('Project changed since it was loaded.'),{status:409,currentRevision:old.revision});const next={...old,...input,id:undefined,clientId:undefined,revision:undefined,contextSnapshot:undefined,businessPackId:undefined,businessPackVersion:undefined,recipeId:undefined,createdAt:undefined,updatedAt:undefined};delete next.expectedRevision;next.language=String(next.language||old.contextSnapshot?.language||'english').trim().slice(0,80);next.generation=repairGeneration(next.generation);next.slides=normalizeSlides(next,old);if(next.templateId!==old.templateId)next.slides=next.slides.map(s=>({...s,artwork:'',artworkAssetId:'',artworkReviewed:false,artworkReviewedAt:''}));if(next.language!==old.language)next.slides=next.slides.map(s=>({...s,approved:false,approvedAt:'',artwork:'',artworkAssetId:'',artworkReviewed:false,artworkReviewedAt:''}));const rev=old.revision+1,updated=now();db.prepare('UPDATE projects SET revision=?,project_json=?,archived=?,updated_at=? WHERE id=?').run(rev,json(next),Number(Boolean(input.archived??old.archived)),updated,projectId);return getProject(clientId,projectId)}
export function applyLatestClientSettings(clientId,projectId,expectedRevision){const old=getProject(clientId,projectId),client=getClient(clientId);if(!old||!client)throw Object.assign(new Error('Project or client not found.'),{status:404});if(Number(expectedRevision)!==old.revision)throw Object.assign(new Error('Project changed since it was loaded.'),{status:409,currentRevision:old.revision});const context=resolveBusinessContext(client);const project={...old,slides:old.slides.map(s=>({...s,approved:false,approvedAt:'',artwork:'',artworkAssetId:'',artworkReviewed:false,artworkReviewedAt:''}))};for(const k of ['id','clientId','revision','archived','businessPackId','businessPackVersion','recipeId','contextSnapshot','createdAt','updatedAt'])delete project[k];db.prepare('UPDATE projects SET revision=?,context_json=?,project_json=?,updated_at=? WHERE id=?').run(old.revision+1,json(context),json(project),now(),projectId);return getProject(clientId,projectId)}
export async function storeAsset(clientId,{projectId='',kind='upload',name='asset',mime='application/octet-stream',bytes}){if(clientId&&!getClient(clientId))throw Object.assign(new Error('Client not found.'),{status:404});const assetId=id(),ext=mime==='image/png'?'.png':mime==='image/jpeg'?'.jpg':mime==='image/webp'?'.webp':'.bin',dir=path.join(assetsRoot,clientId||'_shared');await mkdir(dir,{recursive:true});const file=path.join(dir,assetId+ext);await writeFile(file,bytes);const checksum=hash(bytes);db.prepare('INSERT INTO assets VALUES(?,?,?,?,?,?,?,?,?,?)').run(assetId,clientId,projectId||null,kind,String(name).slice(0,200),mime,bytes.length,checksum,file,now());return getAsset(clientId,assetId)}
export function getAsset(clientId,assetId){const r=db.prepare('SELECT * FROM assets WHERE id=?').get(assetId);if(!r||!(r.client_id===null||r.client_id===clientId))return null;return{id:r.id,clientId:r.client_id,projectId:r.project_id,kind:r.kind,fileName:r.file_name,mime:r.mime,size:r.size,checksum:r.checksum,path:r.path,createdAt:r.created_at}}
export function listTemplates(clientId,businessPackId){return db.prepare("SELECT * FROM templates WHERE archived=0 AND (client_id=? OR client_id IS NULL) AND (business_pack_id IS NULL OR business_pack_id=? OR business_pack_id='') ORDER BY created_at DESC").all(clientId,businessPackId).map(r=>({id:r.id,clientId:r.client_id,packId:r.pack_id,packVersion:r.pack_version,name:r.name,businessPackId:r.business_pack_id,mode:r.mode,data:parse(r.data_json),checksum:r.checksum,createdAt:r.created_at}))}
export function listSharedTemplates(){return db.prepare('SELECT * FROM templates WHERE archived=0 AND client_id IS NULL ORDER BY business_pack_id,name').all().map(r=>({id:r.id,clientId:null,packId:r.pack_id,packVersion:r.pack_version,name:r.name,businessPackId:r.business_pack_id,mode:r.mode,data:parse(r.data_json),checksum:r.checksum,createdAt:r.created_at}))}
export function getTemplate(clientId,templateId){const r=db.prepare('SELECT * FROM templates WHERE id=? AND archived=0').get(templateId);if(!r||!(r.client_id===null||r.client_id===clientId))return null;return{id:r.id,clientId:r.client_id,packId:r.pack_id,packVersion:r.pack_version,name:r.name,businessPackId:r.business_pack_id,mode:r.mode,data:parse(r.data_json),checksum:r.checksum}}
export function installTemplateRecords(clientId,records){
  const insert=db.prepare('INSERT INTO templates VALUES(?,?,?,?,?,?,?,?,?,?,?)');
  const tx=db.transaction(()=>{for(const t of records){
    const existing=db.prepare('SELECT * FROM templates WHERE id=?').get(t.id);
    if(existing){if(existing.checksum===t.checksum)continue;throw Object.assign(new Error('This template version already exists with different content.'),{status:409});}
    insert.run(t.id,clientId||null,t.packId,t.packVersion,t.name,t.businessPackId||null,t.mode,json(t.data),t.checksum,0,now());
  }});tx();return true;
}

export function attachArtworkIfCurrent(clientId,projectId,{slideIndex,copyRevision,templateId,contextHash,assetId,provider}){
  const current=getProject(clientId,projectId);if(!current)throw Object.assign(new Error('Project not found.'),{status:404});
  const slide=current.slides?.[slideIndex];if(!slide||Number(slide.copyRevision)!==Number(copyRevision)||String(current.templateId||'')!==String(templateId||'')||hash(Buffer.from(JSON.stringify(current.contextSnapshot)))!==contextHash)return null;
  const slides=current.slides.map((s,i)=>i===slideIndex?{...s,artworkAssetId:assetId,artworkProvider:provider,artworkGeneratedAt:now(),artworkRevision:(Number(s.artworkRevision)||0)+1,artworkReviewed:false,artworkReviewedAt:''}:s);
  const project={...current,slides};for(const k of ['id','clientId','revision','archived','businessPackId','businessPackVersion','recipeId','contextSnapshot','createdAt','updatedAt'])delete project[k];
  db.prepare('UPDATE projects SET revision=?,project_json=?,updated_at=? WHERE id=?').run(current.revision+1,json(project),now(),projectId);return getProject(clientId,projectId);
}

export function createJob({clientId,projectId,slideIndex=null,stage,provider,model='',inputHash,input,idempotencyKey=''}){if(idempotencyKey){const old=db.prepare('SELECT * FROM jobs WHERE client_id=? AND project_id=? AND idempotency_key=?').get(clientId,projectId,idempotencyKey);if(old)return old}const job={id:id(),client_id:clientId,project_id:projectId,slide_index:slideIndex,stage,provider,model,input_hash:inputHash,input_json:json(input),status:'queued',attempt:1,result_json:null,error:null,idempotency_key:idempotencyKey||null,created_at:now(),started_at:null,finished_at:null};db.prepare('INSERT INTO jobs VALUES(@id,@client_id,@project_id,@slide_index,@stage,@provider,@model,@input_hash,@input_json,@status,@attempt,@result_json,@error,@idempotency_key,@created_at,@started_at,@finished_at)').run(job);return job}
export function finishJob(jobId,status,result,error=''){db.prepare('UPDATE jobs SET status=?,result_json=?,error=?,finished_at=? WHERE id=?').run(status,result?json(result):null,String(error||'').slice(0,1200),now(),jobId)}
export function startJob(jobId){db.prepare("UPDATE jobs SET status='running',started_at=? WHERE id=?").run(now(),jobId)}
export function listJobs(clientId,projectId){return db.prepare('SELECT id,slide_index AS slideIndex,stage,provider,model,status,attempt,error,created_at AS createdAt,started_at AS startedAt,finished_at AS finishedAt FROM jobs WHERE client_id=? AND project_id=? ORDER BY created_at DESC LIMIT 100').all(clientId,projectId)}
export function dashboard(){const clients=db.prepare('SELECT COUNT(*) n FROM clients WHERE archived=0').get().n,projects=db.prepare('SELECT COUNT(*) n FROM projects WHERE archived=0').get().n,review=db.prepare('SELECT project_json FROM projects WHERE archived=0').all().filter(r=>{const p=parse(r.project_json);return p.slides?.some(s=>s.artworkAssetId&&!s.artworkReviewed)}).length,running=db.prepare("SELECT COUNT(*) n FROM jobs WHERE status IN ('queued','running')").get().n;return{clients,projects,review,running}}
export async function importPortableProject(clientId,portable){
  const client=getClient(clientId); if(!client) throw Object.assign(new Error('Client not found.'),{status:404});
  const source=portable?.project; if(!source||!Array.isArray(source.slides)||source.slides.length!==5) throw Object.assign(new Error('Invalid portable project.'),{status:400});
  if(source.businessPackId&&source.businessPackId!==client.businessPackId) throw Object.assign(new Error('Portable project business type does not match the target client.'),{status:400});
  const created=createProject(clientId,{topic:source.topic,key:source.key,notes:source.notes,language:source.language,slides:source.slides,generation:source.generation,stage:source.stage,instagram:source.instagram,youtubeTitle:source.youtubeTitle,youtubeDescription:source.youtubeDescription});
  const embedded=portable.embeddedAssets||{}; const slides=created.slides.map(s=>({...s,artworkAssetId:'',artworkReviewed:false,artworkReviewedAt:''}));
  for(let i=0;i<slides.length;i++){const data=embedded.artworks?.[slides[i].id];if(!data)continue;const m=/^data:(image\/(?:png|jpeg|webp));base64,([A-Za-z0-9+/=]+)$/.exec(String(data));if(!m)continue;const asset=await storeAsset(clientId,{projectId:created.id,kind:'imported-artwork',name:`slide-${i+1}`,mime:m[1],bytes:Buffer.from(m[2],'base64')});slides[i].artworkAssetId=asset.id;slides[i].artworkReviewed=Boolean(source.slides[i]?.artworkReviewed);slides[i].artworkReviewedAt=slides[i].artworkReviewed?String(source.slides[i]?.artworkReviewedAt||now()):'';}
  let templateId='';
  if(embedded.template?.mode&&Array.isArray(embedded.template.images)&&embedded.template.images.length){const t=embedded.template,assets=[];for(let i=0;i<t.images.length;i++){const m=/^data:(image\/(?:png|jpeg|webp));base64,([A-Za-z0-9+/=]+)$/.exec(String(t.images[i]));if(!m)throw Object.assign(new Error('Portable template image is invalid.'),{status:400});assets.push(await storeAsset(clientId,{kind:'imported-template-reference',name:`template-${i+1}`,mime:m[1],bytes:Buffer.from(m[2],'base64')}));}templateId=`portable:${created.id}:template`;const data=t.mode==='slides'?{slides:assets.slice(0,5).map((a,i)=>({position:i+1,assetId:a.id}))}:{assetId:assets[0].id,crops:t.crops||[]};installTemplateRecords(clientId,[{id:templateId,packId:`portable-${created.id}`,packVersion:'1.0.0',name:String(t.name||'Imported project template'),businessPackId:client.businessPackId,mode:t.mode,data,checksum:hash(Buffer.from(JSON.stringify({mode:t.mode,images:t.images.map(x=>hash(Buffer.from(x)))})))}]);}
  let logoAssetId='';if(embedded.logo){const m=/^data:(image\/(?:png|jpeg|webp));base64,([A-Za-z0-9+/=]+)$/.exec(String(embedded.logo));if(m){const a=await storeAsset(clientId,{kind:'imported-project-logo',name:'logo',mime:m[1],bytes:Buffer.from(m[2],'base64')});logoAssetId=a.id;}}
  const context={...(source.contextSnapshot||created.contextSnapshot),brand:{...(source.contextSnapshot?.brand||created.contextSnapshot.brand),logoAssetId}};
  const project={...source,templateId:templateId||source.templateId||'',slides};for(const k of ['id','clientId','revision','archived','createdAt','updatedAt'])delete project[k];
  db.prepare('UPDATE projects SET context_json=?,project_json=?,updated_at=? WHERE id=?').run(json(context),json(project),now(),created.id);
  return getProject(clientId,created.id);
}

export function migrationReport(){const files=fs.existsSync(legacyProjectsRoot)?fs.readdirSync(legacyProjectsRoot).filter(x=>x.endsWith('.json')):[];return{legacyProjects:files.length,legacyTemplateBoards:fs.existsSync(legacyTemplatesRoot)?fs.readdirSync(legacyTemplatesRoot).filter(x=>x.endsWith('.png')).length:0,dryRun:true}}
export async function migrateLegacy(){
  const report=migrationReport();if(!report.legacyProjects&&!report.legacyTemplateBoards)return{...report,migrated:0};
  const backup=path.join(storageRoot,'legacy-backup');await mkdir(backup,{recursive:true});let migrated=0;
  if(!fs.existsSync(legacyProjectsRoot))return{...report,dryRun:false,migrated};
  for(const f of await readdir(legacyProjectsRoot)){if(!f.endsWith('.json'))continue;const source=path.join(legacyProjectsRoot,f),bytes=await readFile(source),checksum=hash(bytes);if(db.prepare('SELECT 1 FROM migration_ledger WHERE source=?').get(f))continue;await cp(source,path.join(backup,f),{force:false}).catch(()=>{});
    try{const p=JSON.parse(bytes.toString());if(!Array.isArray(p.slides)||p.slides.length!==5)throw new Error('invalid legacy project');const legacyBrand=p.brand&&typeof p.brand==='object'?p.brand:{},name=String(legacyBrand.name||"Dr. Pooja's Smile Craft Dental Clinic").trim(),phone=String(legacyBrand.phone||'').trim();let target=listClients({includeArchived:true}).find(c=>String(c.brand?.name||c.name).trim()===name&&String(c.brand?.phone||'').trim()===phone);if(!target)target=createClient({name,businessPackId:'dental',brand:{name,phone,location:legacyBrand.location||'',tagline:legacyBrand.tagline||'',primary:legacyBrand.primary||'#073a42',accent:legacyBrand.accent||'#14ada9'}});
      const templateMap={editorial:'builtin:dental:legacy:editorial:1.0.0',friendly:'builtin:dental:legacy:friendly:1.0.0',clean:'builtin:dental:legacy:clean:1.0.0',premium:'builtin:dental:legacy:premium:1.0.0'};for(const [legacyId] of legacySpecs)templateMap[legacyId]=`builtin:dental:legacy:${legacyId}:1.0.0`;let templateId=templateMap[p.template]||'';
      if(!templateId&&Array.isArray(p.customTemplates)){const custom=p.customTemplates.find(t=>t.id===p.template&&/^data:image\/(?:png|jpeg|webp);base64,/i.test(t.img||''));if(custom){const m=/^data:(image\/(?:png|jpeg|webp));base64,([A-Za-z0-9+/=]+)$/i.exec(custom.img),a=await storeAsset(target.id,{kind:'legacy-template-reference',name:custom.name||'custom-template',mime:m[1],bytes:Buffer.from(m[2],'base64')});templateId=`legacy-custom:${f}:${custom.id}`;installTemplateRecords(target.id,[{id:templateId,packId:`legacy-${target.id}`,packVersion:'1.0.0',name:custom.name||'Legacy custom reference',businessPackId:'dental',mode:'slides',data:{slides:Array.from({length:5},(_,i)=>({position:i+1,assetId:a.id}))},checksum:a.checksum}]);}}
      const created=createProject(target.id,{topic:p.topic,key:p.key,notes:p.notes,language:p.language,slides:p.slides,instagram:p.instagram,youtubeTitle:p.youtubeTitle,youtubeDescription:p.youtubeDescription,generation:p.generation,stage:p.stage,templateId});const slides=created.slides.map((s,i)=>({...s,...p.slides[i],artworkAssetId:'',artworkReviewed:false,artworkReviewedAt:''}));for(let i=0;i<slides.length;i++){const art=String(p.slides[i]?.artwork||'');const m=/^data:(image\/(?:png|jpeg|webp));base64,([A-Za-z0-9+/=]+)$/i.exec(art);if(m){const a=await storeAsset(target.id,{projectId:created.id,kind:'legacy-artwork',name:`slide-${i+1}`,mime:m[1],bytes:Buffer.from(m[2],'base64')});slides[i].artworkAssetId=a.id;slides[i].artwork='';slides[i].artworkReviewed=false;}}
      let logoAssetId='';const lm=/^data:(image\/(?:png|jpeg|webp));base64,([A-Za-z0-9+/=]+)$/i.exec(String(legacyBrand.logo||''));if(lm){const a=await storeAsset(target.id,{kind:'legacy-logo',name:'logo',mime:lm[1],bytes:Buffer.from(lm[2],'base64')});logoAssetId=a.id;}
      const context={...created.contextSnapshot,brand:{...created.contextSnapshot.brand,...legacyBrand,logoAssetId}};const project={...p,templateId,slides};for(const k of ['id','clientId','revision','archived','businessPackId','businessPackVersion','recipeId','contextSnapshot','createdAt','updatedAt'])delete project[k];db.prepare('UPDATE projects SET context_json=?,project_json=?,updated_at=? WHERE id=?').run(json(context),json(project),now(),created.id);db.prepare('INSERT INTO migration_ledger VALUES(?,?,?,?)').run(f,checksum,now(),json({projectId:created.id,clientId:target.id}));migrated++;
    }catch(e){db.prepare('INSERT INTO migration_ledger VALUES(?,?,?,?)').run(f,checksum,now(),json({error:e.message}))}
  }
  return{...report,dryRun:false,migrated,backupPath:backup};
}
