import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { inflateRawSync } from 'node:zlib';
import { mkdir, readFile, writeFile, rm } from 'node:fs/promises';
import { db, storageRoot, storeAsset, installTemplateRecords } from './store.mjs';
import { getBusinessPack } from './business-packs.mjs';

const MAX_ZIP=Number(process.env.TEMPLATE_ZIP_MAX_BYTES)||90_000_000;
const MAX_EXPANDED=Number(process.env.TEMPLATE_ZIP_MAX_EXPANDED_BYTES)||220_000_000;
const MAX_FILES=Number(process.env.TEMPLATE_ZIP_MAX_FILES)||200;
const MAX_IMAGE=Number(process.env.TEMPLATE_IMAGE_MAX_BYTES)||20_000_000;
const importsRoot=path.join(storageRoot,'template-imports'); await mkdir(importsRoot,{recursive:true});
const now=()=>new Date().toISOString(); const id=()=>crypto.randomUUID(); const sha=v=>crypto.createHash('sha256').update(v).digest('hex');
const crcTable=Array.from({length:256},(_,n)=>{let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;return c>>>0});
function crc32(buf){let c=0xffffffff;for(const b of buf)c=crcTable[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0}
function safeName(name){const normalized=path.posix.normalize(String(name).replace(/\\/g,'/'));if(!normalized||normalized.startsWith('/')||normalized.startsWith('../')||normalized.includes('/../')||/^[a-z]:/i.test(normalized))throw Object.assign(new Error(`Unsafe ZIP path: ${name}`),{status:400});return normalized}
function findEocd(bytes){for(let i=Math.max(0,bytes.length-65557);i<=bytes.length-22;i++){if(bytes.readUInt32LE(i)===0x06054b50)return i}throw Object.assign(new Error('ZIP central directory not found.'),{status:400})}
export function parseZip(bytes){if(!Buffer.isBuffer(bytes))bytes=Buffer.from(bytes);if(bytes.length>MAX_ZIP)throw Object.assign(new Error('Template ZIP is too large.'),{status:413});const eocd=findEocd(bytes),count=bytes.readUInt16LE(eocd+10),centralOffset=bytes.readUInt32LE(eocd+16);if(count>MAX_FILES)throw Object.assign(new Error('Template ZIP has too many files.'),{status:400});const entries=[];let pos=centralOffset,total=0;const seen=new Set();for(let i=0;i<count;i++){if(bytes.readUInt32LE(pos)!==0x02014b50)throw Object.assign(new Error('Invalid ZIP central directory.'),{status:400});const flags=bytes.readUInt16LE(pos+8),method=bytes.readUInt16LE(pos+10),expectedCrc=bytes.readUInt32LE(pos+16),compressed=bytes.readUInt32LE(pos+20),size=bytes.readUInt32LE(pos+24),nameLen=bytes.readUInt16LE(pos+28),extraLen=bytes.readUInt16LE(pos+30),commentLen=bytes.readUInt16LE(pos+32),external=bytes.readUInt32LE(pos+38),localOffset=bytes.readUInt32LE(pos+42);const rawName=bytes.subarray(pos+46,pos+46+nameLen).toString('utf8'),name=safeName(rawName);pos+=46+nameLen+extraLen+commentLen;if(name.endsWith('/'))continue;if((external>>>16&0o170000)===0o120000)throw Object.assign(new Error('Symlinks are not allowed in template ZIPs.'),{status:400});if(flags&1)throw Object.assign(new Error('Encrypted ZIPs are not supported.'),{status:400});if(![0,8].includes(method))throw Object.assign(new Error(`Unsupported ZIP compression method for ${name}.`),{status:400});if(seen.has(name))throw Object.assign(new Error(`Duplicate ZIP path: ${name}`),{status:400});seen.add(name);total+=size;if(total>MAX_EXPANDED)throw Object.assign(new Error('Expanded ZIP would exceed the configured limit.'),{status:400});if(bytes.readUInt32LE(localOffset)!==0x04034b50)throw Object.assign(new Error(`Invalid local ZIP entry for ${name}.`),{status:400});const localNameLen=bytes.readUInt16LE(localOffset+26),localExtra=bytes.readUInt16LE(localOffset+28),start=localOffset+30+localNameLen+localExtra,end=start+compressed;if(end>bytes.length)throw Object.assign(new Error(`Truncated ZIP entry: ${name}`),{status:400});const packed=bytes.subarray(start,end),data=method===0?Buffer.from(packed):inflateRawSync(packed);if(data.length!==size)throw Object.assign(new Error(`ZIP size mismatch for ${name}.`),{status:400});if(crc32(data)!==expectedCrc)throw Object.assign(new Error(`ZIP CRC mismatch for ${name}.`),{status:400});entries.push({name,data,size,method})}return entries}
function imageInfo(bytes){if(bytes.length>MAX_IMAGE)throw new Error('Image exceeds per-file limit.');if(bytes.subarray(0,8).equals(Buffer.from('89504e470d0a1a0a','hex'))){if(bytes.length<24)throw new Error('Invalid PNG.');return{mime:'image/png',width:bytes.readUInt32BE(16),height:bytes.readUInt32BE(20)}}if(bytes[0]===0xff&&bytes[1]===0xd8){let p=2;while(p+9<bytes.length){if(bytes[p]!==0xff){p++;continue}const marker=bytes[p+1],len=bytes.readUInt16BE(p+2);if([0xc0,0xc1,0xc2,0xc3,0xc5,0xc6,0xc7,0xc9,0xca,0xcb,0xcd,0xce,0xcf].includes(marker))return{mime:'image/jpeg',height:bytes.readUInt16BE(p+5),width:bytes.readUInt16BE(p+7)};p+=Math.max(2,len+2)}throw new Error('Invalid JPEG.')}if(bytes.subarray(0,4).toString()==='RIFF'&&bytes.subarray(8,12).toString()==='WEBP')return{mime:'image/webp',width:0,height:0};throw new Error('Only PNG, JPEG and WebP image files are supported.')}
const legacyCrops={
  'teal-editorial-pro':{top:.205,bottom:.744,left:.006,right:.006,gap:.005},'clinical-white':{top:.205,bottom:.752,left:.006,right:.006,gap:.005},'warm-ivory':{top:.064,bottom:.811,left:.006,right:.006,gap:.005},'deep-teal-premium':{top:.181,bottom:.848,left:.006,right:.006,gap:.005},'mint-friendly':{top:.158,bottom:.864,left:.006,right:.006,gap:.005},'airy-aqua':{top:.160,bottom:.824,left:.006,right:.006,gap:.005},'kids-mint':{top:.177,bottom:.866,left:.006,right:.006,gap:.005},'nature-sage':{top:.172,bottom:.826,left:.006,right:.006,gap:.005},'warm-clinical':{top:.205,bottom:.915,left:.006,right:.006,gap:.005},'premium-charcoal':{top:.163,bottom:.736,left:.006,right:.006,gap:.005}
};
function previewEntries(entries,businessPackId){const manifestEntry=entries.find(e=>e.name==='pack.json');let manifest=null;if(manifestEntry){try{manifest=JSON.parse(manifestEntry.data.toString('utf8'))}catch{throw Object.assign(new Error('pack.json is not valid JSON.'),{status:400})}}const images=[];for(const entry of entries){if(/^(__MACOSX\/|\.DS_Store$)/.test(entry.name)||entry.name==='pack.json'||entry.name==='manifest.json'||/\.(?:json|txt|md)$/i.test(entry.name))continue;try{const info=imageInfo(entry.data);images.push({name:entry.name,size:entry.size,...info})}catch(e){throw Object.assign(new Error(`${entry.name}: ${e.message}`),{status:400})}}if(!images.length)throw Object.assign(new Error('No supported images were found in the ZIP.'),{status:400});if(manifest){if(Number(manifest.schemaVersion)!==1)throw Object.assign(new Error('Unsupported template pack schemaVersion.'),{status:400});if(!manifest.id||!manifest.version||!Array.isArray(manifest.templates))throw Object.assign(new Error('pack.json requires id, version and templates.'),{status:400});const names=new Set(images.map(i=>i.name));for(const t of manifest.templates){if(!['slides','board'].includes(t.mode))throw Object.assign(new Error('Template mode must be slides or board.'),{status:400});if(t.mode==='slides'){if(!Array.isArray(t.slides)||t.slides.length!==5)throw Object.assign(new Error(`${t.name||t.id}: exactly five slide images are required.`),{status:400});const positions=t.slides.map(s=>Number(s.position)).sort((a,b)=>a-b);if(positions.some((v,i)=>v!==i+1))throw Object.assign(new Error(`${t.name||t.id}: slide positions must be 1 through 5.`),{status:400});for(const s of t.slides)if(!names.has(s.image))throw Object.assign(new Error(`Missing image ${s.image}.`),{status:400})}else{if(!names.has(t.image)||!Array.isArray(t.crops)||t.crops.length!==5)throw Object.assign(new Error(`${t.name||t.id}: board mode needs one image and five crops.`),{status:400});for(const c of t.crops){for(const k of ['x','y','width','height'])if(!Number.isFinite(Number(c[k])))throw Object.assign(new Error(`${t.name||t.id}: crop ${k} must be numeric.`),{status:400});const x=Number(c.x),y=Number(c.y),w=Number(c.width),h=Number(c.height);if(x<0||y<0||w<=0||h<=0||x+w>1||y+h>1)throw Object.assign(new Error(`${t.name||t.id}: crop rectangles must stay within normalized 0–1 bounds.`),{status:400})}}}return{kind:'manifest',manifest,images,unresolved:false}}
const legacy=Object.keys(legacyCrops).filter(id=>images.some(i=>i.name.endsWith(`${id}.png`)));if(legacy.length===10)return{kind:'legacy-smilecraft',images,unresolved:false,packId:'smilecraft-masters',version:'1.0.0',templates:legacy.map(x=>({id:x,name:x.replace(/-/g,' '),mode:'board',image:images.find(i=>i.name.endsWith(`${x}.png`)).name,crops:Array.from({length:5},(_,position)=>({position:position+1,...legacyCrops[x]}))}))};if(images.length===5)return{kind:'image-only',images,unresolved:false,packId:`${businessPackId||'general'}-import`,version:'1.0.0',templates:[{id:'five-slide-reference',name:'Five-slide reference',mode:'slides',slides:images.sort((a,b)=>a.name.localeCompare(b.name)).map((x,i)=>({position:i+1,image:x.name}))}]};return{kind:'image-only',images,unresolved:true,packId:`${businessPackId||'general'}-import`,version:'1.0.0',templates:[]}}
export async function stageTemplateImport({clientId,businessPackId,scope='client',bytes}){if(!['client','shared'].includes(scope))throw Object.assign(new Error('Template scope must be client or shared.'),{status:400});getBusinessPack(businessPackId);if(scope==='client'&&!clientId)throw Object.assign(new Error('Client scope requires clientId.'),{status:400});if(scope==='shared')clientId=null;const checksum=sha(bytes),old=db.prepare('SELECT * FROM template_imports WHERE checksum=? AND client_id=? ORDER BY created_at DESC LIMIT 1').get(checksum,clientId);if(old&&old.status==='staged')return{id:old.id,preview:JSON.parse(old.preview_json),duplicate:true};const entries=parseZip(bytes),preview=previewEntries(entries,businessPackId),importId=id(),dir=path.join(importsRoot,importId);await mkdir(dir,{recursive:true});const zipPath=path.join(dir,'pack.zip');await writeFile(zipPath,bytes);db.prepare('INSERT INTO template_imports VALUES(?,?,?,?,?,?,?,?,?,?)').run(importId,clientId,businessPackId,scope,'staged',checksum,zipPath,JSON.stringify(preview),now(),new Date(Date.now()+24*3600e3).toISOString());return{id:importId,preview,duplicate:false}}
export function updateTemplateImport(importId,patch){const row=db.prepare('SELECT * FROM template_imports WHERE id=?').get(importId);if(!row)throw Object.assign(new Error('Template import not found.'),{status:404});if(row.status!=='staged')throw Object.assign(new Error('Template import is no longer editable.'),{status:409});const preview=JSON.parse(row.preview_json);if(patch.packId)preview.packId=String(patch.packId).trim().slice(0,80);if(patch.version)preview.version=String(patch.version).trim().slice(0,40);if(Array.isArray(patch.templates))preview.templates=patch.templates;if(!preview.templates?.length)throw Object.assign(new Error('Map at least one template before installation.'),{status:400});db.prepare('UPDATE template_imports SET preview_json=? WHERE id=?').run(JSON.stringify(preview),importId);return preview}
export async function installTemplateImport(importId){
  const row=db.prepare('SELECT * FROM template_imports WHERE id=?').get(importId);if(!row)throw Object.assign(new Error('Template import not found.'),{status:404});if(row.status==='installed')return{ok:true,idempotent:true};if(row.status!=='staged')throw Object.assign(new Error('Template import is not installable.'),{status:409});
  const bytes=await readFile(row.staged_path),entries=parseZip(bytes),byName=new Map(entries.map(e=>[e.name,e])),preview=JSON.parse(row.preview_json),manifest=preview.manifest;
  const packId=String(manifest?.id||preview.packId||'imported-pack'),packVersion=String(manifest?.version||preview.version||'1.0.0'),templates=manifest?.templates||preview.templates;if(!Array.isArray(templates)||!templates.length)throw Object.assign(new Error('Template mappings are incomplete.'),{status:400});
  const plans=[];
  for(const t of templates){const mode=t.mode,refs=mode==='slides'?t.slides.map(s=>s.image):[t.image];const sourceHashes=[];for(const image of refs){const entry=byName.get(image);if(!entry)throw Object.assign(new Error(`Missing image ${image}.`),{status:400});imageInfo(entry.data);sourceHashes.push(sha(entry.data));}const templateId=`${packId}:${t.id||'template'}:${packVersion}:${row.client_id}`,checksum=sha(Buffer.from(JSON.stringify({packId,packVersion,businessPackId:row.business_pack_id,mode,mapping:t,sourceHashes}))),existing=db.prepare('SELECT * FROM templates WHERE id=?').get(templateId);if(existing&&existing.checksum!==checksum)throw Object.assign(new Error('This template version already exists with different content. Use a new version or pack ID.'),{status:409});plans.push({t,mode,refs,templateId,checksum,existing});}
  const records=[];for(const plan of plans){if(plan.existing)continue;const assets=[];for(const image of plan.refs){const entry=byName.get(image),info=imageInfo(entry.data);assets.push(await storeAsset(row.client_id,{kind:'template-reference',name:image,mime:info.mime,bytes:entry.data}));}const data=plan.mode==='slides'?{slides:plan.t.slides.map((s,i)=>({position:i+1,assetId:assets[i].id}))}:{assetId:assets[0].id,crops:plan.t.crops};records.push({id:plan.templateId,packId,packVersion,name:String(plan.t.name||plan.t.id||'Template'),businessPackId:row.business_pack_id,mode:plan.mode,data,checksum:plan.checksum});}
  installTemplateRecords(row.client_id,records);db.prepare("UPDATE template_imports SET status='installed' WHERE id=?").run(importId);return{ok:true,idempotent:records.length===0,templates:plans.map(x=>({id:x.templateId,name:String(x.t.name||x.t.id||'Template')}))};
}
export async function cleanupImports(){const rows=db.prepare("SELECT * FROM template_imports WHERE status='staged' AND expires_at<?").all(now());for(const r of rows){db.prepare("UPDATE template_imports SET status='expired' WHERE id=?").run(r.id);await rm(path.dirname(r.staged_path),{recursive:true,force:true})}}
