import {IMAGE_MODELS,WRITING_MODELS} from '../web/provider-models.js';
import {apiStructured} from '../server/v4/text-api.mjs';
import {artworkPrompt} from '../server/v4/content-prompts.mjs';
import {createV4Service} from '../server/v4/service.mjs';
import {STYLE_REFERENCES,stylePrompt} from '../server/v4/image-prompts.mjs';
const fail=(message,status=409)=>Object.assign(Error(message),{status});
const base64=bytes=>{let str='';for(let i=0;i<bytes.length;i+=8192)str+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(str)};
const unbase64=str=>Uint8Array.from(atob(str),c=>c.charCodeAt(0));
function findImage(value){if(!value||typeof value!=='object')return null;if(value.b64_json)return {bytes:unbase64(value.b64_json),mime:'image/png'};if(typeof value.data==='string'&&(value.mime_type||value.mimeType))return {bytes:unbase64(value.data),mime:value.mime_type||value.mimeType||'image/png'};for(const child of Object.values(value)){if(typeof child!=='object')continue;if(Array.isArray(child)){for(const item of child){const found=findImage(item);if(found)return found}}else{const found=findImage(child);if(found)return found}}return null}
export function cloudV4(env){
 const defaultProvider=env.OPENAI_API_KEY?'openai':env.GEMINI_API_KEY?'gemini':null;
 async function activation(account){const row=await env.DB.prepare(`SELECT s.plan_id,s.status,p.monthly_credits FROM subscriptions s JOIN plans p ON p.id=s.plan_id AND p.version=s.plan_version WHERE s.account_id=?`).bind(account).first();const balance=await env.DB.prepare(`SELECT COALESCE((SELECT SUM(amount) FROM credit_ledger WHERE account_id=? AND (expires_at IS NULL OR expires_at>datetime('now'))),0)-COALESCE((SELECT SUM(amount) FROM credit_reservations WHERE account_id=? AND status='reserved'),0) credits`).bind(account,account).first();return {active:Boolean(row&&['active','trialing','manual'].includes(row.status)&&row.monthly_credits>0),mode:'manual',credits:balance?.credits||0}}
 async function requireActivation(account){const state=await activation(account);if(!state.active)throw fail('Your clinic is awaiting activation. Your team will activate access after confirming payment.');if(!defaultProvider)throw fail('Image generation is not connected yet. Your team needs to configure the service.');if(!env.IMAGES)throw fail('Image optimisation is not configured.');if(state.credits<10)throw fail('Your clinic needs a credit top-up from your team.',402)}
 async function privateImage(account,clinic,id){if(!id)return null;const row=await env.DB.prepare('SELECT original_key,mime FROM v4_assets WHERE id=? AND account_id=? AND clinic_id=?').bind(id,account,clinic).first();if(!row)return null;const object=await env.ASSETS.get(row.original_key);return object?{bytes:new Uint8Array(await object.arrayBuffer()),mime:row.mime}:null}
 async function generate(c,prompt,references,ratio,signal,generation){await requireActivation(c.account_id);const creditId=crypto.randomUUID();const debit=await env.DB.prepare(`INSERT INTO credit_ledger(id,account_id,amount,kind,source_id) SELECT ?,?,-10,'v4_generation',? WHERE (SELECT COALESCE(SUM(amount),0) FROM credit_ledger WHERE account_id=? AND (expires_at IS NULL OR expires_at>datetime('now')))-(SELECT COALESCE(SUM(amount),0) FROM credit_reservations WHERE account_id=? AND status='reserved')>=10`).bind(creditId,c.account_id,creditId,c.account_id,c.account_id).run();if(!debit.meta.changes)throw fail('Your clinic needs a credit top-up from your team.',402);
  const provider=generation?.provider||defaultProvider,model=generation?.model||env.SRSHTI_IMAGE_MODEL||(provider==='openai'?'gpt-image-1':'gemini-3.1-flash-image');
  try{let response;if(provider==='openai'){const form=new FormData();form.append('model',model);form.append('prompt',prompt);form.append('size',ratio==='1:1'?'1024x1024':ratio==='4:3'?'1536x1024':'1024x1536');form.append('quality','medium');form.append('output_format','png');for(const [i,ref] of references.filter(Boolean).entries())form.append('image[]',new Blob([ref.bytes],{type:ref.mime}),`reference-${i}.png`);response=await fetch('https://api.openai.com/v1/images/edits',{method:'POST',headers:{Authorization:`Bearer ${env.OPENAI_API_KEY}`},body:form,signal:signal?AbortSignal.any([signal,AbortSignal.timeout(240000)]):AbortSignal.timeout(240000)});}else{response=await fetch('https://generativelanguage.googleapis.com/v1beta/interactions',{method:'POST',headers:{'x-goog-api-key':env.GEMINI_API_KEY,'Content-Type':'application/json'},body:JSON.stringify({model:model,input:[{type:'text',text:prompt},...references.filter(Boolean).map(ref=>({type:'image',mime_type:ref.mime,data:base64(ref.bytes)}))],response_format:{type:'image',mime_type:'image/png',aspect_ratio:ratio,image_size:'2K'}}),signal:signal?AbortSignal.any([signal,AbortSignal.timeout(240000)]):AbortSignal.timeout(240000)});}if(!response.ok)throw fail(`Image service rejected this task (${response.status}). Please retry.`,502);const image=findImage(await response.json());if(!image)throw fail('The image service returned no artwork. Please retry.',502);
   // Persist exact social-format canvas sizes, including when provider sizes are coarse.
   if(ratio!=='4:3'){const width=1080,height=ratio==='9:16'?1920:ratio==='1:1'?1080:1350;const output=await env.IMAGES.input(new Response(image.bytes).body).transform({width,height,fit:'pad',background:'#ffffff'}).output({format:'image/png'});return {bytes:new Uint8Array(await output.response().arrayBuffer()),mime:'image/png',creditId}}return {...image,creditId};
  }catch(error){await env.DB.prepare("INSERT OR IGNORE INTO credit_ledger(id,account_id,amount,kind,source_id) VALUES(?,?,10,'v4_refund',?)").bind(crypto.randomUUID(),c.account_id,`refund:${creditId}`).run();throw error}
 }
 return createV4Service({providerCatalog:async()=>Object.fromEntries(['openai','gemini','claude','codex','antigravity'].map(p=>[p,{label:{openai:'OpenAI API',gemini:'Gemini API',claude:'Claude API',codex:'Codex CLI',antigravity:'Antigravity CLI'}[p],available:Boolean({openai:env.OPENAI_API_KEY,gemini:env.GEMINI_API_KEY,claude:env.ANTHROPIC_API_KEY}[p]),models:['openai','gemini'].includes(p)?(IMAGE_MODELS[p]||[]).filter(([id])=>id===(env.SRSHTI_IMAGE_MODEL||(p==='openai'?'gpt-image-1':'gemini-3.1-flash-image'))).concat((IMAGE_MODELS[p]||[]).filter(([id])=>id!==(env.SRSHTI_IMAGE_MODEL||(p==='openai'?'gpt-image-1':'gemini-3.1-flash-image')))):[],writingModels:WRITING_MODELS[p]||[],detail:['codex','antigravity'].includes(p)?'CLI providers are available in the local workspace.':'Availability depends on the configured server key.'}])),db:env.DB,activation,requireActivation,capabilities:{generation:Boolean(defaultProvider),demo:false,optimizedImages:Boolean(env.IMAGES),publishing:false,billing:false},enqueue:async id=>env.GENERATION.send({v4JobId:id}),
  async saveImage(account,clinic,image){if(!env.IMAGES)throw fail('Image optimisation is not configured.');const prefix=`${account}/v4/${clinic}/${crypto.randomUUID()}`,originalKey=`${prefix}/original`,previewKey=`${prefix}/preview.webp`,thumbnailKey=`${prefix}/thumb.webp`;const originals=new Uint8Array(image.bytes);const resize=async width=>{const out=await env.IMAGES.input(new Response(originals).body).transform({width}).output({format:'image/webp',quality:width===1000?78:72});return out.response().arrayBuffer()};const [preview,thumb,info]=await Promise.all([resize(1000),resize(400),env.IMAGES.info(new Response(originals).body)]);await Promise.all([env.ASSETS.put(originalKey,originals,{httpMetadata:{contentType:image.mime}}),env.ASSETS.put(previewKey,preview,{httpMetadata:{contentType:'image/webp'}}),env.ASSETS.put(thumbnailKey,thumb,{httpMetadata:{contentType:'image/webp'}})]);return {mime:image.mime,originalKey,previewKey,thumbnailKey,width:info.width||null,height:info.height||null,size:originals.byteLength};},
  async refundImage(account,image){if(image.creditId)await env.DB.prepare("INSERT OR IGNORE INTO credit_ledger(id,account_id,amount,kind,source_id) VALUES(?,?,10,'v4_refund',?)").bind(crypto.randomUUID(),account,`refund:${image.creditId}`).run();},
  async readImage(key){const obj=await env.ASSETS.get(key);return obj?{bytes:await obj.arrayBuffer(),mime:obj.httpMetadata?.contentType}:null},
  async generateText({generation,prompt,schema,reference,signal,account}){
   const state=await activation(account);if(!state.active)throw fail('Your clinic is awaiting activation.');
   const cost=schema.properties.frames?2:1,creditId=crypto.randomUUID();
   const charged=await env.DB.prepare(`INSERT INTO credit_ledger(id,account_id,amount,kind,source_id) SELECT ?,?,?,'v4_writing',? WHERE (SELECT COALESCE(SUM(amount),0) FROM credit_ledger WHERE account_id=? AND (expires_at IS NULL OR expires_at>datetime('now')))-(SELECT COALESCE(SUM(amount),0) FROM credit_reservations WHERE account_id=? AND status='reserved')>=?`).bind(creditId,account,-cost,creditId,account,account,cost).run();if(!charged.meta.changes)throw fail('Your clinic needs a credit top-up from your team.',402);
   try{return await apiStructured({...generation,prompt,schema,reference,signal,env});}catch(error){await env.DB.prepare("INSERT OR IGNORE INTO credit_ledger(id,account_id,amount,kind,source_id) VALUES(?,?,?,'v4_refund',?)").bind(crypto.randomUUID(),account,cost,`refund:${creditId}`).run();throw error;}
  },
  async generateStyle(c,reference,jobId,generation,signal){const references=await Promise.all(STYLE_REFERENCES.map(async ref=>{const response=await env.STATIC.fetch(new Request(`${env.APP_ORIGIN}/assets/design-systems/${ref}.png`));if(!response.ok)throw fail('Design reference unavailable.',502);return {bytes:new Uint8Array(await response.arrayBuffer()),mime:'image/png'};}));return generate(c,stylePrompt(c,reference),[...references,await privateImage(c.account_id,c.id,c.brand.logoAssetId)],'4:3',signal,generation)},
  async generateFrame(c,item,frame,style,jobId,generation,signal){const reference=await privateImage(c.account_id,c.id,style?.asset_id);if(!reference)throw fail('The selected clinic style is unavailable.');return generate(c,artworkPrompt(c,item,frame),[reference,await privateImage(c.account_id,c.id,c.brand.logoAssetId)],item.type==='story'?'9:16':item.type==='post'?'1:1':'4:5',signal,generation)}
 });
}
