import { TOPICS, TEMPLATES, ROLES, newProject, starterSlides, captionFallback } from './data.js';
import { renderThumb, renderPngBlob, optimizedImage } from './canvas.js';
import { makeZip, downloadBlob, dataURLBlob } from './zip.js';

const el = document.querySelector('#app');
const state = { view: 'home', project: newProject(), index: 0, busy: '', status: {}, projects: [], captionTab: 'instagram', toastTimer: null, renderNonce: 0, saving: false, changeTimer: null, correction: '', includeCaptions: true, includeProject: true };
const e = value => String(value ?? '').replace(/[&<>"']/g, ch => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[ch]);
const text = s => e(s).replace(/\n/g, '<br>');
const $ = selector => document.querySelector(selector);
const activeTemplate = () => [...TEMPLATES, ...(state.project.customTemplates || [])].find(t => t.id === state.project.template) || TEMPLATES[0];
const approvedCount = () => state.project.slides.filter(s => s.approved).length;
const current = () => state.project.slides[state.index];
const section = (title, sub = '') => `<div class="header-row"><div><h1 class="page-title">${e(title)}</h1><p class="subtitle">${e(sub)}</p></div><span class="pill">${approvedCount()} / 5 approved</span></div>`;
function toast(message) { const node = $('#toast'); node.textContent = message; node.classList.add('show'); clearTimeout(state.toastTimer); state.toastTimer = setTimeout(() => node.classList.remove('show'), 5800); }
async function api(url, data, method = data === undefined ? 'GET' : 'POST') {
  const res = await fetch(url, { method, headers: { 'Content-Type': 'application/json' }, body: data === undefined ? undefined : JSON.stringify(data) });
  let json; try { json = await res.json(); } catch { throw new Error(`Request failed (${res.status}).`); }
  if (!res.ok) throw new Error(json.error || `Request failed (${res.status}).`);
  return json;
}
async function listProjects() { try { state.projects = (await api('/api/projects')).projects; } catch (err) { toast(err.message); } }
async function saveProject(show = false) {
  if (!state.project.topic.trim() || state.saving) return;
  state.saving = true; const savingProject = state.project;
  try {
    const result = await api('/api/projects', savingProject);
    if (state.project === savingProject) { savingProject.id = result.id; savingProject.updatedAt = result.updatedAt; }
    if (show) toast('Project saved locally. You can reopen it from My Projects.');
  } catch (err) { toast(`Could not save: ${err.message}`); } finally { state.saving = false; }
}
function scheduleSave() { clearTimeout(state.changeTimer); state.changeTimer = setTimeout(() => saveProject(), 1200); }
function workflow() { const steps = ['Topic', 'Content', 'Design', 'Review', 'Export']; const stage = Math.max(0, Number(state.project.stage) || 0); return `<div class="stepbar" aria-label="Carousel workflow">${steps.map((name, i) => `<button class="step ${stage === i ? 'active' : i < stage ? 'done' : ''}" data-action="stage" data-index="${i}"><span class="stepnum">${i < stage ? '✓' : i + 1}</span>${name}</button>`).join('')}</div>`; }
function nav() { const navs = [['home', '⌂', 'Home'], ['create', '▧', 'Create Carousel'], ['projects', '▣', 'My Projects'], ['templates', '▦', 'Templates'], ['brand', '⚙', 'Brand Settings']]; return `<aside class="side"><div class="logo"><span>♧</span><div class="wordmark">SmileCraft <span style="color:#0d9b9d">AI</span><small style="display:block">Social Media Creator</small></div></div><nav>${navs.map(([key, icon, label]) => `<button class="navitem ${state.view === key ? 'active' : ''}" data-action="nav" data-value="${key}"><span class="navicon">${icon}</span>${label}</button>`).join('')}</nav><div class="side-bottom"><strong>✦ Local-first studio</strong>Draft words with your locally authenticated Codex CLI. Keep editing control, preview each slide and export individual PNGs.</div></aside>`; }
function shell(content) { return `<div class="shell">${nav()}<main class="main"><header class="topbar"><div class="crumb">SmileCraft Studio <span> / </span><strong>${state.view === 'create' ? ['Topic', 'Content', 'Design', 'Review', 'Export'][state.project.stage || 0] : state.view === 'home' ? 'Dashboard' : state.view === 'brand' ? 'Brand Settings' : state.view === 'templates' ? 'Templates' : 'My Projects'}</strong></div><div class="userpill"><span class="avatar">S</span> SmileCraft Dental Clinic</div></header>${content}</main></div>`; }
function home() { const tiles = state.projects.slice(0, 4).map(p => `<button class="project-tile" data-action="open-project" data-id="${e(p.id)}"><img src="${e(activeTemplate().img || '/assets/teal-editorial.jpg')}" alt="Carousel example"><div class="tile-info"><b>${e(p.topic || 'Untitled')}</b><small>5 slides · ${e((p.updatedAt || '').slice(0, 10))}</small></div></button>`).join('');
  return `<div class="dashboard-hero"><div><span class="pill">✦ Make scroll-stopping education simple</span><h1 class="headline">Create beautiful<br><b>dental carousels</b><br>in minutes.</h1><p>Turn one idea into five approved Malayalam slides. Choose a visual direction, add photos, review every page and export an upload-ready ZIP.</p><button class="btn primary big" data-action="new">＋ Create New Carousel →</button></div><div class="dashboard-visual">${['teal-editorial.jpg','friendly-clinic.jpg','premium-dark.jpg'].map(n => `<img src="/assets/${n}" alt="Sample SmileCraft carousel layout">`).join('')}</div></div><div class="feature-row"><div class="feature"><span>✍</span> Approval-first writing</div><div class="feature"><span>◈</span> Clean design templates</div><div class="feature"><span>▣</span> Separate PNG slides</div><div class="feature"><span>↡</span> Organized ZIP & captions</div></div><div class="header-row"><div><h2 style="font-size:19px;margin:0 0 6px">Recent projects</h2><p class="subtitle">Open a saved project and continue where you left off.</p></div><button class="btn tiny" data-action="nav" data-value="projects">View all →</button></div>${tiles ? `<div class="projects-grid">${tiles}</div>` : `<div class="empty"><div class="emicon">▧</div>No saved projects yet. Create your first carousel to see it here.</div>`}`; }
function topicPage() { return `${section('Create New Carousel', 'Tell us your idea. Build one clean page at a time, with your approval before production.')}${workflow()}<div class="grid-2"><section class="card card-pad"><span class="pill">STEP 01 · YOUR IDEA</span><h2 style="margin-top:18px">What should your carousel be about?</h2><p class="subtitle">Add your topic in Malayalam or English. Codex can draft the five pages; you always review the wording.</p><label class="formlabel" for="topic">Carousel topic or question</label><textarea id="topic" data-field="topic" class="control biginput" maxlength="450" placeholder="ഉദാ: പല്ല് ക്ലീൻ ചെയ്താൽ പല്ലുകൾക്ക് ഇടയിൽ വിടവ് വരുമോ?">${e(state.project.topic)}</textarea><label class="formlabel" for="notes">Extra context (optional)</label><textarea id="notes" data-field="notes" class="control area" placeholder="Target audience, points to cover, style, details to avoid…">${e(state.project.notes || '')}</textarea><div class="subhead">Or choose a popular topic</div><div class="chips">${TOPICS.map(topic => `<button class="chip ${state.project.topic === topic.topic ? 'selected' : ''}" data-action="choose-topic" data-value="${e(topic.key)}">${e(topic.label)}</button>`).join('')}</div><div class="actions"><span class="hint">Codex CLI runs locally on your computer; no API key is used for writing.</span><button class="btn primary" data-action="draft" ${state.busy ? 'disabled' : ''}>${state.busy === 'draft' ? '<span class="spinner"></span> Drafting…' : '✦ Generate slide copy →'}</button></div><div class="note amber" style="margin-top:15px">${state.status.codexAvailable === false ? '<b>Codex CLI was not detected on this machine.</b> Install it and run <code>codex login</code> first. ' : ''}Codex not installed yet? Pick a suggested topic, then use <b>Start with editable sample</b>. Sample copy is not AI-generated and must be reviewed before publication.</div><button class="btn soft" data-action="sample" style="margin-top:12px">Start with editable sample →</button></section><aside class="card card-pad"><span class="pill">Your publishing flow</span><div class="intro-art" style="margin-top:13px"><strong>One idea.<br>Five beautiful pages.</strong><div class="hero-icon">🦷</div><div>WRITE → APPROVE → DESIGN → DOWNLOAD</div></div><div class="subhead">What gets created?</div><div class="note">01 Hook · 02 Science · 03 Impact · 04 Action · 05 CTA. Only the last slide has a booking call-to-action.</div></aside></div>`; }
function slideTabs() { return `<div class="slide-tabs">${state.project.slides.map((s, i) => `<button class="slide-tab ${state.index === i ? 'active' : ''} ${s.approved ? 'approved' : ''}" data-action="select-slide" data-index="${i}"><strong>Slide ${i + 1}</strong>${ROLES[i]}</button>`).join('')}</div>`; }
function previewImg(i, klass = '') { return `<img class="${klass}" data-preview-index="${i}" alt="Preview of carousel slide ${i + 1}" src="" loading="lazy">`; }
function contentPage() { const s = current(); return `${section('Review your slide copy', 'Edit every page, request a specific correction from Codex, and approve all five before export.')}${workflow()}<div class="card card-pad">${slideTabs()}<div class="two-col-editor"><section><div class="meta-row"><h2>Slide ${state.index + 1} — ${e(s.role)}</h2><span class="pill ${s.approved ? 'green' : 'amber'}">${s.approved ? '✓ Approved' : '○ Needs approval'}</span></div><label class="formlabel" for="heading">Headline</label><textarea id="heading" data-field="heading" class="control area textarea-small" maxlength="100">${e(s.heading)}</textarea><label class="formlabel" for="body">Supporting text · keep it short</label><textarea id="body" data-field="body" class="control area textarea-small" maxlength="240">${e(s.body)}</textarea><label class="formlabel" for="visualPrompt">Image idea for this slide</label><textarea id="visualPrompt" data-field="visualPrompt" class="control area textarea-small" maxlength="550">${e(s.visualPrompt)}</textarea><label class="formlabel" for="correction">Ask Codex for a correction (optional)</label><textarea id="correction" class="control area textarea-small" placeholder="ഉദാ: ഇത് കൂടുതൽ ലളിതമായ മലയാളത്തിൽ എഴുതൂ…">${e(state.correction)}</textarea><div class="actions"><button class="btn soft" data-action="revise" ${state.busy ? 'disabled' : ''}>${state.busy === 'revise' ? 'Rewriting…' : '✦ Rewrite this slide'}</button><button class="btn ${s.approved ? '' : 'primary'}" data-action="approve">${s.approved ? '↶ Reopen slide' : '✓ Approve this slide'}</button></div><p class="hint">Any text edit or AI revision reopens the slide for review. No booking CTA on slides 1–4.</p></section><aside><div class="editor-preview preview-frame loading">${previewImg(state.index)}</div><div class="note" style="margin-top:15px">Live preview uses the chosen layout and your uploaded photo, or an included dental illustration. You can change the imagery on the Design step.</div></aside></div><div class="actions"><button class="btn" data-action="stage" data-index="0">← Topic</button><button class="btn primary" data-action="stage" data-index="2">Choose a template →</button></div></div>`; }
function templateCard(t) { return `<button class="template-card ${state.project.template === t.id ? 'selected' : ''}" data-action="choose-template" data-value="${e(t.id)}"><img src="${e(t.img)}" alt="${e(t.name)} reference appearance"><span class="check">${state.project.template === t.id ? '●' : '○'}</span><strong>${e(t.name)}</strong><small>${e(t.kind)} · ${e(t.layout)}</small></button>`; }
function designPage() { return `${section('Choose your visual style', 'Reference cards show inspiration. The app creates new layouts instead of stamping new words over old posters.')}${workflow()}<div class="card card-pad"><div class="header-row"><div><h2>3. Select a template</h2><p class="subtitle">Choose a clean layout. Upload your own reference image to keep it in this project.</p></div><span class="pill">${e(activeTemplate().name)}</span></div><div class="template-grid">${[...TEMPLATES, ...(state.project.customTemplates || [])].map(templateCard).join('')}</div><label class="file-upload" style="margin-top:16px"><input type="file" accept="image/png,image/jpeg,image/webp" data-file-action="template"><span>＋ Upload your own sample template image (preview reference)<br><small>Stored with this project. It is not used as a text-filled background.</small></span></label></div><div class="grid-side" style="margin-top:18px"><section class="card card-pad"><h2>Add imagery for each slide</h2><p class="subtitle">The included tooth illustrations work offline. For photo-led carousels, upload a photo or use the optional AI image provider.</p>${slideTabs()}<div class="setting-grid"><label class="file-upload"><input type="file" accept="image/png,image/jpeg,image/webp" data-file-action="slide-image"><span>▧ <b>Upload slide ${state.index + 1} image</b><br><small>PNG, JPG or WebP, up to 16 MB</small></span></label><div class="note"><b>AI photo (optional)</b><br>Uses a separate image-generation API key; image costs are not covered by Codex CLI login.<br><button class="btn tiny soft" style="margin-top:10px" data-action="generate-image" ${state.busy ? 'disabled' : ''}>${state.busy === 'image' ? 'Generating…' : '✦ Generate AI photo'}</button></div></div><div class="actions"><button class="btn tiny" data-action="clear-image">Use built-in illustration instead</button><span class="pill ${current().image ? 'green' : 'muted'}">${current().image ? `${e(current().imageSource)} image selected` : 'Built-in illustration'}</span></div></section><aside class="card card-pad"><h2>Live design preview</h2><div class="editor-preview preview-frame loading" style="margin-top:15px">${previewImg(state.index)}</div><div class="actions"><button class="btn tiny" data-action="stage" data-index="1">← Edit copy</button><button class="btn primary" data-action="stage" data-index="3">Review 5 slides →</button></div></aside></div>`; }
function reviewPage() { return `${section('Preview your carousel', 'See the final five-slide sequence. Go back and edit text, imagery or colors whenever you need.')}${workflow()}<div class="card card-pad"><div class="meta-row"><h2>4. Final review</h2><span class="pill ${approvedCount() === 5 ? 'green' : 'amber'}">${approvedCount() === 5 ? 'All slides approved' : `${5 - approvedCount()} slide(s) still need approval`}</span></div><div class="review-strip">${state.project.slides.map((s, i) => `<button class="review-slide ${i === state.index ? 'active' : ''}" data-action="select-slide" data-index="${i}">${previewImg(i)}<small>0${i + 1} · ${e(s.role)} ${s.approved ? '✓' : '○'}</small></button>`).join('')}</div><div class="review-layout" style="margin-top:21px"><div class="big-preview preview-frame loading">${previewImg(state.index)}</div><div><h2>Slide ${state.index + 1} · ${e(current().role)}</h2><p class="subtitle" style="margin-bottom:15px">${e(current().heading)}</p><p style="font-size:13px;color:#637f87;line-height:1.75">${e(current().body)}</p><div class="note" style="margin-top:20px">Your PNGs are rendered at <b>1080 × 1350 (4:5)</b>, ideal for Instagram feed carousels. Preview text is drawn by the browser; check Malayalam glyphs before posting.</div><div class="actions"><button class="btn soft" data-action="stage" data-index="1">✎ Edit copy</button><button class="btn soft" data-action="stage" data-index="2">◈ Change design</button></div><div class="actions"><button class="btn tiny" data-action="download-one">↡ Download this PNG</button><button class="btn primary" data-action="stage" data-index="4">Export options →</button></div></div></div></div>`; }
function captionField() { const p = state.project; const fallback = captionFallback(p); const key = state.captionTab; const val = p[key] || fallback[key]; return `<div class="caption-tabs">${[['instagram','Instagram caption'],['youtubeTitle','YouTube title'],['youtubeDescription','YouTube description']].map(([k,label]) => `<button class="btn tiny ${key === k ? 'active' : ''}" data-action="caption-tab" data-value="${k}">${label}</button>`).join('')}</div><textarea class="control captionbox" data-field="${key}" aria-label="${e(key)}">${e(val)}</textarea><div class="actions"><span class="hint">${p[key] ? 'Edited/generated copy' : 'Auto-composed from your current slides; review before publishing.'}</span><button class="btn tiny" data-action="copy-caption">Copy ${e(key)}</button></div>`; }
function exportPage() { return `${section('Export your carousel', 'Download the five individual slides, ready-to-copy captions and an editable project backup.')}${workflow()}<div class="grid-side"><section class="card card-pad"><h2>5. Choose your deliverables</h2><p class="subtitle">Each exported PNG is a complete slide, not a crop from a single combined image.</p><div class="export-grid"><button class="export-option selected" data-action="noop"><span class="bigicon">▧</span><b>Images (ZIP)</b><small>5 individually rendered PNGs, 1080 × 1350</small></button><button class="export-option ${state.includeCaptions ? 'selected' : ''}" data-action="toggle-captions"><span class="bigicon">♧</span><b>Social captions ${state.includeCaptions ? '✓' : ''}</b><small>Instagram copy and YouTube title + description</small></button><button class="export-option ${state.includeProject ? 'selected' : ''}" data-action="toggle-project"><span class="bigicon">▤</span><b>Editable project ${state.includeProject ? '✓' : ''}</b><small>Importable JSON with layouts, copy and uploaded imagery</small></button><button class="export-option" data-action="download-one"><span class="bigicon">↡</span><b>Single PNG</b><small>Download the slide selected in Review</small></button></div><div class="note ${approvedCount() < 5 ? 'amber' : ''}">${approvedCount() < 5 ? `Approve the remaining ${5 - approvedCount()} slide(s) in the Content step to enable full export.` : 'All five slides approved. Your upload-ready ZIP can be generated locally in this browser.'}</div><div class="actions right"><button class="btn" data-action="stage" data-index="3">← Review</button><button class="btn primary big" data-action="export" ${approvedCount() < 5 || state.busy ? 'disabled' : ''}>${state.busy === 'export' ? '<span class="spinner"></span> Rendering PNGs…' : '↡ Generate & Download ZIP'}</button></div></section><aside class="card card-pad"><h2>Social copy</h2><p class="subtitle">Edit the copy before export. It will be saved in plain-text files inside the ZIP.</p>${captionField()}</aside></div>`; }
function brandPage() { const b = state.project.brand; return `<div class="header-row"><div><h1 class="page-title">Brand Settings</h1><p class="subtitle">Keep your clinic signature consistent. Updates apply to this project and its export.</p></div><button class="btn primary" data-action="save">Save branding</button></div><div class="grid-side"><section class="card card-pad"><h2>Your clinic identity</h2><label class="formlabel">Clinic / brand name</label><input class="control" data-brand="name" maxlength="45" value="${e(b.name)}"><label class="formlabel">Brand subtitle</label><input class="control" data-brand="tagline" maxlength="40" value="${e(b.tagline)}"><div class="setting-grid"><div><label class="formlabel">Background shade</label><input type="color" data-brand="primary" value="${e(b.primary)}"><span class="hint">${e(b.primary)}</span></div><div><label class="formlabel">Accent shade</label><input type="color" data-brand="accent" value="${e(b.accent)}"><span class="hint">${e(b.accent)}</span></div></div><label class="formlabel">Optional logo</label><label class="file-upload"><input type="file" accept="image/png,image/jpeg,image/webp" data-file-action="logo">＋ Upload your logo (prefer a simple transparent PNG)</label><p class="hint">The PNG's actual transparency is preserved best with a small logo file. Uploaded photos are compressed for local project storage.</p><div class="actions"><button class="btn tiny" data-action="clear-logo">Clear logo</button><button class="btn primary" data-action="stage" data-index="3">View branded slides →</button></div></section><aside class="card card-pad"><h2>Brand preview</h2><div class="editor-preview preview-frame loading" style="margin-top:13px">${previewImg(state.index)}</div><div class="note" style="margin-top:15px">Color and branding changes update every slide. Reference thumbnails remain unchanged.</div></aside></div>`; }
function projectsPage() { return `<div class="header-row"><div><h1 class="page-title">My Projects</h1><p class="subtitle">Locally saved in the app's <code>storage/projects</code> folder on this computer.</p></div><div class="actions" style="margin:0"><label class="btn" for="project-import">↑ Import project JSON</label><input type="file" accept="application/json,.json" id="project-import" data-file-action="import" hidden><button class="btn primary" data-action="new">＋ New carousel</button></div></div><div class="project-list">${state.projects.length ? state.projects.map(p => `<div class="project-row"><div class="project-emoji">🦷</div><div class="rowinfo"><strong>${e(p.topic)}</strong><small>Updated ${e((p.updatedAt || '').slice(0, 16).replace('T', ' '))} · ${e(p.template)}</small></div><span class="mini-stat">${p.approved}/5 approved</span><button class="btn tiny primary" data-action="open-project" data-id="${e(p.id)}">Open →</button><button class="btn tiny danger" data-action="delete-project" data-id="${e(p.id)}">Delete</button></div>`).join('') : `<div class="empty"><div class="emicon">▣</div>No saved projects yet.</div>`}</div>`; }
function templateLibraryPage() { return `<div class="header-row"><div><h1 class="page-title">Template Library</h1><p class="subtitle">Browse layouts and example images, then choose one when creating your carousel.</p></div><button class="btn primary" data-action="nav" data-value="create">Open carousel editor →</button></div><div class="card card-pad"><div class="template-grid">${[...TEMPLATES, ...(state.project.customTemplates || [])].map(templateCard).join('')}</div><div class="note" style="margin-top:20px">Uploaded reference images are preview examples, not editable layered templates. Your final slide artwork is generated with clean native layouts, your text and optional uploaded/AI-generated photos.</div></div>`; }
function render() {
  const stage = Number(state.project.stage) || 0;
  let content = state.view === 'home' ? home() : state.view === 'projects' ? projectsPage() : state.view === 'brand' ? brandPage() : state.view === 'templates' ? templateLibraryPage() : stage === 0 ? topicPage() : stage === 1 ? contentPage() : stage === 2 ? designPage() : stage === 3 ? reviewPage() : exportPage();
  el.innerHTML = shell(content);
  refreshPreviews();
}
async function refreshPreviews() {
  const nonce = ++state.renderNonce;
  const targets = [...document.querySelectorAll('img[data-preview-index]')];
  const unique = [...new Set(targets.map(node => Number(node.dataset.previewIndex)))];
  for (const i of unique) {
    try {
      const url = await renderThumb({ ...state.project, templates: TEMPLATES }, i);
      if (state.renderNonce !== nonce) return;
      for (const img of targets) if (Number(img.dataset.previewIndex) === i && img.isConnected) {
        img.src = url; img.parentElement?.classList.remove('loading');
      }
    } catch (err) { if (state.renderNonce === nonce) toast(`Preview error: ${err.message}`); }
  }
}
async function showView(view) { if (view === 'create') state.project.stage = state.project.stage ?? 0; if (view === 'projects' || view === 'home') await listProjects(); state.view = view; render(); }
function gotoStage(number) { state.project.stage = Math.max(0, Math.min(4, Number(number))); state.view = 'create'; if (state.project.stage === 4 && state.project.slides.some(s => !s.approved)) toast('Approve all five slides in Content before full export. You can still preview this screen.'); scheduleSave(); render(); }
function setTopic(topic, key = '') { const prev = state.project; if (prev.topic && prev.topic !== topic && prev.slides.some(s => s.approved) && !confirm('Replace this project topic and its slide drafts?')) return; state.project = newProject(topic, key); state.project.brand = { ...prev.brand }; state.project.customTemplates = prev.customTemplates; state.index = 0; state.correction = ''; render(); scheduleSave(); }
async function generateDraft() {
  const topic = state.project.topic.trim(); if (!topic) return toast('Enter a carousel topic first.');
  state.busy = 'draft'; render();
  try {
    const { draft } = await api('/api/draft', { topic, notes: state.project.notes });
    state.project.slides = draft.slides; state.project.instagram = draft.instagram; state.project.youtubeTitle = draft.youtubeTitle; state.project.youtubeDescription = draft.youtubeDescription; state.project.stage = 1; state.index = 0; state.correction = ''; scheduleSave(); toast('Codex drafted five slides. Review and approve them one by one.');
  } catch (err) { toast(`Could not draft: ${err.message}`); } finally { state.busy = ''; render(); }
}
async function rewriteSlide() {
  const correction = ($('#correction')?.value || '').trim(); if (!correction) return toast('Describe the change you want Codex to make.');
  state.busy = 'revise'; render();
  try { const { slide } = await api('/api/revise', { topic: state.project.topic, slide: current(), correction }); Object.assign(current(), slide, { approved: false }); state.correction = ''; scheduleSave(); toast('Slide rewritten. Review the new text before approving.'); }
  catch (err) { toast(`Could not revise: ${err.message}`); } finally { state.busy = ''; render(); }
}
function approveSlide() { const s = current(); if (s.approved) s.approved = false; else { if (!s.heading.trim() || !s.body.trim()) return toast('Add a heading and body before approving.'); s.approved = true; if (state.index < 4) state.index++; } state.correction = ''; scheduleSave(); render(); }
async function generateImage() {
  if (!current().visualPrompt?.trim()) return toast('Add a visual description for this slide first.');
  state.busy = 'image'; render();
  try { const { image } = await api('/api/image', { prompt: current().visualPrompt }); const photo = await optimizedImage(dataURLBlob(image), 1024); Object.assign(current(), { image: photo, imageSource: 'AI-generated' }); scheduleSave(); toast('Image generated for this slide. Review the clinical accuracy before publishing.'); }
  catch (err) { toast(`Image generation unavailable: ${err.message}`); } finally { state.busy = ''; render(); }
}
function getSocialCopy() { const c = captionFallback(state.project); return { instagram: state.project.instagram || c.instagram, youtubeTitle: state.project.youtubeTitle || c.youtubeTitle, youtubeDescription: state.project.youtubeDescription || c.youtubeDescription }; }
async function downloadOne() { state.busy = 'export'; render(); try { const png = await renderPngBlob({ ...state.project, templates: TEMPLATES }, state.index); downloadBlob(png, `${String(state.index + 1).padStart(2, '0')}.png`); } catch (err) { toast(err.message); } finally { state.busy = ''; render(); } }
function folderName() { return (state.project.key || state.project.topic || 'dental-carousel').normalize('NFKD').replace(/[^a-zA-Z0-9-]/g, '-').replace(/-+/g, '-').replace(/^-|-$/g, '').slice(0, 45) || 'dental-carousel'; }
async function exportZip() {
  if (approvedCount() !== 5) return toast('Approve all five slides before full export.');
  state.busy = 'export'; render();
  try {
    const dir = `smilecraft_${folderName()}`, entries = [];
    for (let i = 0; i < 5; i++) entries.push({ name: `${dir}/${String(i + 1).padStart(2, '0')}.png`, data: await renderPngBlob({ ...state.project, templates: TEMPLATES }, i) });
    const captions = getSocialCopy();
    if (state.includeCaptions) {
      entries.push({ name: `${dir}/instagram_caption.txt`, data: captions.instagram }, { name: `${dir}/youtube_title.txt`, data: captions.youtubeTitle }, { name: `${dir}/youtube_description.txt`, data: captions.youtubeDescription });
    }
    if (state.includeProject) entries.push({ name: `${dir}/project.json`, data: JSON.stringify({ ...state.project, ...captions }, null, 2) });
    entries.push({ name: `${dir}/README.txt`, data: 'Five distinct 1080x1350 PNG slides. Post 01.png through 05.png in order. Images are illustrations or user/AI-supplied visual assets; have a clinician verify medical claims and images. Project JSON can be imported from My Projects.\n' });
    downloadBlob(await makeZip(entries), `${dir}.zip`);
    await saveProject(); toast('ZIP downloaded with five separate PNGs and your selected deliverables.');
  } catch (err) { toast(`Could not export: ${err.message}`); } finally { state.busy = ''; render(); }
}
async function openProject(id) { try { const { project } = await api(`/api/projects/${encodeURIComponent(id)}`); state.project = project; state.index = 0; state.view = 'create'; state.correction = ''; render(); } catch (err) { toast(err.message); } }
function directUpdate(target) {
  const p = state.project, field = target.dataset.field, brand = target.dataset.brand;
  if (brand) { p.brand[brand] = target.value; if (brand === 'primary' || brand === 'accent') p.brand.paletteOverride = true; scheduleSave(); if (target.type === 'color') refreshPreviews(); return; }
  if (!field) return;
  if (field === 'topic' || field === 'notes' || ['instagram', 'youtubeTitle', 'youtubeDescription'].includes(field)) p[field] = target.value;
  else if (['heading', 'body', 'visualPrompt'].includes(field)) { current()[field] = target.value; current().approved = false; clearTimeout(state.previewTimer); state.previewTimer = setTimeout(refreshPreviews, 380); }
  scheduleSave();
}
async function onFileInput(target) {
  const file = target.files?.[0]; if (!file) return;
  try {
    const purpose = target.dataset.fileAction;
    if (purpose === 'import') {
      const p = JSON.parse(await file.text()); if (!p || !Array.isArray(p.slides) || p.slides.length !== 5 || !p.brand) throw new Error('Not a SmileCraft five-slide project.');
      state.project = { ...newProject(), ...p, id: '', updatedAt: '' }; state.index = 0; state.view = 'create'; state.project.stage = 1; render(); await saveProject(true); return;
    }
    const image = await optimizedImage(file, purpose === 'logo' ? 400 : 1150);
    if (purpose === 'logo') state.project.brand.logo = image;
    if (purpose === 'slide-image') Object.assign(current(), { image, imageSource: 'uploaded' });
    if (purpose === 'template') {
      const id = `custom-${Date.now()}`; state.project.customTemplates ||= [];
      state.project.customTemplates.push({ id, name: file.name.replace(/\.[^.]+$/, '').slice(0, 35) || 'My reference', kind: 'Uploaded reference', img: image, dark: '#073a42', teal: '#16aba5', light: '#b5eeeb', layout: 'split' }); state.project.template = id;
    }
    scheduleSave(); render(); toast('Image added to this local project.');
  } catch (err) { toast(`Could not add file: ${err.message}`); }
}
async function onAction(node) {
  const action = node.dataset.action, value = node.dataset.value, i = Number(node.dataset.index), id = node.dataset.id;
  if (state.busy && !['nav', 'select-slide'].includes(action)) return;
  switch (action) {
    case 'noop': return;
    case 'nav': return showView(value);
    case 'new': state.project = newProject(); state.index = 0; state.view = 'create'; return render();
    case 'stage': return gotoStage(i);
    case 'choose-topic': { const preset = TOPICS.find(t => t.key === value); return setTopic(preset?.topic || '', preset?.key || ''); }
    case 'draft': return generateDraft();
    case 'sample': if (!state.project.topic.trim()) return toast('Enter or choose a topic first.'); state.project.slides = starterSlides(state.project.topic); state.project.stage = 1; state.index = 0; scheduleSave(); toast('Editable starter loaded (not AI-generated). Review the medical copy and approve each slide.'); return render();
    case 'select-slide': state.index = i; state.correction = ''; return render();
    case 'approve': return approveSlide();
    case 'revise': return rewriteSlide();
    case 'choose-template': state.project.template = value; scheduleSave(); if (state.view === 'templates') { state.view = 'create'; state.project.stage = 2; } return render();
    case 'generate-image': return generateImage();
    case 'clear-image': current().image = ''; current().imageSource = 'illustration'; scheduleSave(); return render();
    case 'clear-logo': state.project.brand.logo = ''; scheduleSave(); return render();
    case 'save': return saveProject(true);
    case 'toggle-captions': state.includeCaptions = !state.includeCaptions; return render();
    case 'toggle-project': state.includeProject = !state.includeProject; return render();
    case 'caption-tab': state.captionTab = value; return render();
    case 'copy-caption': try { await navigator.clipboard.writeText(getSocialCopy()[state.captionTab]); toast('Caption copied to clipboard.'); } catch { toast('Clipboard unavailable. Select and copy the text manually.'); } return;
    case 'download-one': return downloadOne();
    case 'export': return exportZip();
    case 'open-project': return openProject(id);
    case 'delete-project': if (confirm('Delete this locally saved project? This cannot be undone.')) { try { await api(`/api/projects/${encodeURIComponent(id)}`, undefined, 'DELETE'); await listProjects(); render(); toast('Project deleted.'); } catch (err) { toast(err.message); } } return;
  }
}
el.addEventListener('click', event => { const node = event.target.closest('[data-action]'); if (node) { event.preventDefault(); onAction(node); } });
el.addEventListener('input', event => { if (event.target.id === 'correction') state.correction = event.target.value; else directUpdate(event.target); });
el.addEventListener('change', event => { if (event.target.dataset.fileAction) onFileInput(event.target); });
await listProjects(); try { state.status = await api('/api/status'); } catch {} render();
